// Generated by scripts/build-steam-hardware.mjs. Do not edit by hand.
// Source: Steam Hardware & Software Survey (Valve), snapshot September 2026, read from
//   https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam/?platform=<pc|linux>
// Weights are renormalized marginal probabilities (sum to 1 per category).

import type { SteamHardwareCatalog } from "./hardware-profiles";

export const steamHardwareSurveyDate = "September 2026" as const;

export const steamHardwareCatalog: SteamHardwareCatalog = {
  "windows": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.5036413991178582
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.28474715355421065
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.05569802030977535
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.04933839368140321
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.029541491435018972
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.0263616781208329
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.01959175300030772
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.006257052005333879
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.006051902759257359
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.004923581905836495
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.0036926864293773715
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.0036926864293773715
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.0033849625602625907
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.00307723869114781
      }
    ],
    "cpuCores": [
      {
        "value": 8,
        "weight": 0.3005601120224045
      },
      {
        "value": 6,
        "weight": 0.27845569113822766
      },
      {
        "value": 4,
        "weight": 0.10372074414882976
      },
      {
        "value": 10,
        "weight": 0.07811562312462493
      },
      {
        "value": 16,
        "weight": 0.0588117623524705
      },
      {
        "value": 14,
        "weight": 0.05361072214442889
      },
      {
        "value": 12,
        "weight": 0.04730946189237848
      },
      {
        "value": 24,
        "weight": 0.028805761152230446
      },
      {
        "value": 2,
        "weight": 0.02360472094418884
      },
      {
        "value": 20,
        "weight": 0.021704340868173636
      },
      {
        "value": 18,
        "weight": 0.002400480096019204
      },
      {
        "value": 5,
        "weight": 0.001700340068013603
      },
      {
        "value": 3,
        "weight": 0.0008001600320064014
      },
      {
        "value": 1,
        "weight": 0.00020004000800160035
      },
      {
        "value": 22,
        "weight": 0.00010002000400080017
      },
      {
        "value": 32,
        "weight": 0.00010002000400080017
      }
    ],
    "ram": [
      {
        "value": 32,
        "weight": 0.4389897555533015
      },
      {
        "value": 16,
        "weight": 0.3813774216451972
      },
      {
        "value": 8,
        "weight": 0.061162389694695195
      },
      {
        "value": 64,
        "weight": 0.03742773100720154
      },
      {
        "value": 24,
        "weight": 0.024343239679480676
      },
      {
        "value": 12,
        "weight": 0.0216046252155391
      },
      {
        "value": 48,
        "weight": 0.014707373973019574
      },
      {
        "value": 4,
        "weight": 0.01166446901308449
      },
      {
        "value": 60,
        "weight": 0.008722994218480575
      }
    ]
  },
  "linux": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.4260423945958538
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.2089447938504543
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.08339156766829725
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.05672024225483347
      },
      {
        "value": {
          "width": 1280,
          "height": 800
        },
        "weight": 0.052760307477288625
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.04239459585371537
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.036687631027253684
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.01979967388772421
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.010249242953645474
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.009433962264150948
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.008152806894945262
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.006056370836245052
      },
      {
        "value": {
          "width": 3072,
          "height": 1728
        },
        "weight": 0.005241090146750527
      },
      {
        "value": {
          "width": 1280,
          "height": 720
        },
        "weight": 0.0047752154670393674
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.004658746797111579
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.00454227812718379
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.00419287211740042
      },
      {
        "value": {
          "width": 3840,
          "height": 2400
        },
        "weight": 0.0038434661076170522
      },
      {
        "value": {
          "width": 5120,
          "height": 2880
        },
        "weight": 0.0038434661076170522
      },
      {
        "value": {
          "width": 2256,
          "height": 1504
        },
        "weight": 0.002795248078266947
      },
      {
        "value": {
          "width": 3072,
          "height": 1920
        },
        "weight": 0.002795248078266947
      },
      {
        "value": {
          "width": 2880,
          "height": 1920
        },
        "weight": 0.0026787794083391577
      }
    ],
    "cpuCores": [
      {
        "value": 4,
        "weight": 0.2844284428442845
      },
      {
        "value": 8,
        "weight": 0.2770277027702771
      },
      {
        "value": 6,
        "weight": 0.2148214821482149
      },
      {
        "value": 16,
        "weight": 0.05370537053705372
      },
      {
        "value": 12,
        "weight": 0.05330533053305332
      },
      {
        "value": 2,
        "weight": 0.04300430043004302
      },
      {
        "value": 10,
        "weight": 0.029502950295029515
      },
      {
        "value": 14,
        "weight": 0.019301930193019307
      },
      {
        "value": 24,
        "weight": 0.014201420142014205
      },
      {
        "value": 20,
        "weight": 0.008100810081008105
      },
      {
        "value": 18,
        "weight": 0.0007000700070007004
      },
      {
        "value": 32,
        "weight": 0.0005000500050005003
      },
      {
        "value": 5,
        "weight": 0.00040004000400040016
      },
      {
        "value": 3,
        "weight": 0.0003000300030003001
      },
      {
        "value": 36,
        "weight": 0.00020002000200020008
      },
      {
        "value": 1,
        "weight": 0.00010001000100010004
      },
      {
        "value": 9,
        "weight": 0.00010001000100010004
      },
      {
        "value": 22,
        "weight": 0.00010001000100010004
      },
      {
        "value": 28,
        "weight": 0.00010001000100010004
      },
      {
        "value": 64,
        "weight": 0.00010001000100010004
      }
    ],
    "ram": [
      {
        "value": 16,
        "weight": 0.42000822537528276
      },
      {
        "value": 32,
        "weight": 0.333538967715402
      },
      {
        "value": 8,
        "weight": 0.06261566933991362
      },
      {
        "value": 64,
        "weight": 0.053670573719925965
      },
      {
        "value": 60,
        "weight": 0.033518404277195143
      },
      {
        "value": 12,
        "weight": 0.03331276989512647
      },
      {
        "value": 24,
        "weight": 0.019946535060662143
      },
      {
        "value": 4,
        "weight": 0.019329631914456094
      },
      {
        "value": 28,
        "weight": 0.013057783261361299
      },
      {
        "value": 48,
        "weight": 0.011001439440674481
      }
    ]
  }
};
