// Generated by scripts/build-steam-hardware.mjs. Do not edit by hand.
// Source: Steam Hardware & Software Survey (Valve), snapshot August 2026, read from
//   https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam/?platform=<pc|linux>
// Weights are renormalized marginal probabilities (sum to 1 per category).

import type { SteamHardwareCatalog } from "./hardware-profiles";

export const steamHardwareSurveyDate = "August 2026" as const;

export const steamHardwareCatalog: SteamHardwareCatalog = {
  "windows": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.5353327855382086
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.23058751027115856
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.061729663105998346
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.05156121610517665
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.03204601479046836
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.02865653245686113
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.02290468364831553
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.006984387838948233
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.0068816762530813464
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.005443714050944946
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.004211175020542316
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.004005751848808545
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.004005751848808545
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.0034921939194741164
      },
      {
        "value": {
          "width": 1280,
          "height": 720
        },
        "weight": 0.002156943303204601
      }
    ],
    "cpuCores": [
      {
        "value": 6,
        "weight": 0.28232823282328234
      },
      {
        "value": 8,
        "weight": 0.27952795279527953
      },
      {
        "value": 4,
        "weight": 0.11831183118311833
      },
      {
        "value": 10,
        "weight": 0.07090709070907092
      },
      {
        "value": 16,
        "weight": 0.06100610061006101
      },
      {
        "value": 12,
        "weight": 0.050805080508050805
      },
      {
        "value": 14,
        "weight": 0.05040504050405041
      },
      {
        "value": 24,
        "weight": 0.030803080308030806
      },
      {
        "value": 2,
        "weight": 0.027902790279027905
      },
      {
        "value": 20,
        "weight": 0.022502250225022502
      },
      {
        "value": 18,
        "weight": 0.0021002100210021
      },
      {
        "value": 5,
        "weight": 0.0019001900190019005
      },
      {
        "value": 3,
        "weight": 0.0009000900090009002
      },
      {
        "value": 1,
        "weight": 0.00020002000200020005
      },
      {
        "value": 7,
        "weight": 0.00010001000100010003
      },
      {
        "value": 22,
        "weight": 0.00010001000100010003
      },
      {
        "value": 28,
        "weight": 0.00010001000100010003
      },
      {
        "value": 32,
        "weight": 0.00010001000100010003
      }
    ],
    "ram": [
      {
        "value": 16,
        "weight": 0.4151000606428138
      },
      {
        "value": 32,
        "weight": 0.3888215079846371
      },
      {
        "value": 8,
        "weight": 0.07074994946432181
      },
      {
        "value": 64,
        "weight": 0.04012532848190822
      },
      {
        "value": 12,
        "weight": 0.024560339599757428
      },
      {
        "value": 24,
        "weight": 0.020618556701030927
      },
      {
        "value": 4,
        "weight": 0.013846775823731554
      },
      {
        "value": 48,
        "weight": 0.011926420052557105
      },
      {
        "value": 60,
        "weight": 0.009197493430361836
      },
      {
        "value": 28,
        "weight": 0.005053567818880129
      }
    ]
  },
  "linux": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.42882947976878616
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.19677263969171485
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.0773121387283237
      },
      {
        "value": {
          "width": 1280,
          "height": 800
        },
        "weight": 0.06322254335260116
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.05527456647398844
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.041787090558766865
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.03986030828516378
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.019388246628131024
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.0098747591522158
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.009272639691714837
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.008670520231213874
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.006021194605009635
      },
      {
        "value": {
          "width": 3072,
          "height": 1728
        },
        "weight": 0.005659922928709055
      },
      {
        "value": {
          "width": 1280,
          "height": 720
        },
        "weight": 0.0051782273603082855
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.004696531791907516
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.004696531791907516
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.004576107899807322
      },
      {
        "value": {
          "width": 5120,
          "height": 2880
        },
        "weight": 0.004094412331406552
      },
      {
        "value": {
          "width": 3072,
          "height": 1920
        },
        "weight": 0.003492292870905588
      },
      {
        "value": {
          "width": 2256,
          "height": 1504
        },
        "weight": 0.0030105973025048175
      },
      {
        "value": {
          "width": 3840,
          "height": 2400
        },
        "weight": 0.0030105973025048175
      },
      {
        "value": {
          "width": 1280,
          "height": 1024
        },
        "weight": 0.002890173410404624
      },
      {
        "value": {
          "width": 2880,
          "height": 1920
        },
        "weight": 0.002408477842003854
      }
    ],
    "cpuCores": [
      {
        "value": 4,
        "weight": 0.3229322932293229
      },
      {
        "value": 8,
        "weight": 0.2615261526152615
      },
      {
        "value": 6,
        "weight": 0.1989198919891989
      },
      {
        "value": 12,
        "weight": 0.0513051305130513
      },
      {
        "value": 16,
        "weight": 0.050205020502050196
      },
      {
        "value": 2,
        "weight": 0.046704670467046704
      },
      {
        "value": 10,
        "weight": 0.028002800280028
      },
      {
        "value": 14,
        "weight": 0.018501850185018504
      },
      {
        "value": 24,
        "weight": 0.011801180118011801
      },
      {
        "value": 20,
        "weight": 0.007800780078007801
      },
      {
        "value": 18,
        "weight": 0.0006000600060006
      },
      {
        "value": 5,
        "weight": 0.00040004000400040005
      },
      {
        "value": 32,
        "weight": 0.00040004000400040005
      },
      {
        "value": 1,
        "weight": 0.0003000300030003
      },
      {
        "value": 3,
        "weight": 0.00020002000200020003
      },
      {
        "value": 7,
        "weight": 0.00010001000100010001
      },
      {
        "value": 22,
        "weight": 0.00010001000100010001
      },
      {
        "value": 36,
        "weight": 0.00010001000100010001
      },
      {
        "value": 64,
        "weight": 0.00010001000100010001
      }
    ],
    "ram": [
      {
        "value": 16,
        "weight": 0.44494658997534925
      },
      {
        "value": 32,
        "weight": 0.31152423993426454
      },
      {
        "value": 8,
        "weight": 0.06686524239934263
      },
      {
        "value": 64,
        "weight": 0.04919884963023829
      },
      {
        "value": 12,
        "weight": 0.03286770747740345
      },
      {
        "value": 60,
        "weight": 0.03071076417419885
      },
      {
        "value": 4,
        "weight": 0.02218570254724733
      },
      {
        "value": 24,
        "weight": 0.01910435497124076
      },
      {
        "value": 28,
        "weight": 0.011811832374691866
      },
      {
        "value": 48,
        "weight": 0.010784716516023007
      }
    ]
  }
};
