// Generated by scripts/build-steam-hardware.mjs. Do not edit by hand.
// Source: Steam Hardware & Software Survey (Valve), snapshot July 2026, read from
//   https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam/?platform=<pc|linux>
// Weights are renormalized marginal probabilities (sum to 1 per category).

import type { SteamHardwareCatalog } from "./hardware-profiles";

export const steamHardwareSurveyDate = "July 2026" as const;

export const steamHardwareCatalog: SteamHardwareCatalog = {
  "windows": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.5415898381479205
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.22618315918869084
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.05511165744724442
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.05132145052243393
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.03206310182339685
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.027453390698627334
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.025302192173734896
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.007375537799631223
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.007170661749641466
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.005326777299733661
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.004609711124769515
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.004199959024790001
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.004097520999795125
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.0036877688998156115
      },
      {
        "value": {
          "width": 1280,
          "height": 720
        },
        "weight": 0.002356074574882196
      },
      {
        "value": {
          "width": 1280,
          "height": 1024
        },
        "weight": 0.00215119852489244
      }
    ],
    "cpuCores": [
      {
        "value": 6,
        "weight": 0.28432843284328435
      },
      {
        "value": 8,
        "weight": 0.27742774277427745
      },
      {
        "value": 4,
        "weight": 0.12451245124512453
      },
      {
        "value": 10,
        "weight": 0.06990699069906992
      },
      {
        "value": 16,
        "weight": 0.057705770577057704
      },
      {
        "value": 12,
        "weight": 0.05040504050405041
      },
      {
        "value": 14,
        "weight": 0.04920492049204921
      },
      {
        "value": 2,
        "weight": 0.030703070307030705
      },
      {
        "value": 24,
        "weight": 0.029102910291029106
      },
      {
        "value": 20,
        "weight": 0.021702170217021706
      },
      {
        "value": 5,
        "weight": 0.0020002000200020006
      },
      {
        "value": 18,
        "weight": 0.0015001500150015003
      },
      {
        "value": 3,
        "weight": 0.0009000900090009002
      },
      {
        "value": 1,
        "weight": 0.00020002000200020005
      },
      {
        "value": 7,
        "weight": 0.00010001000100010003
      },
      {
        "value": 22,
        "weight": 0.00010001000100010003
      },
      {
        "value": 28,
        "weight": 0.00010001000100010003
      },
      {
        "value": 32,
        "weight": 0.00010001000100010003
      }
    ],
    "ram": [
      {
        "value": 16,
        "weight": 0.41219290263876246
      },
      {
        "value": 32,
        "weight": 0.3844909513699323
      },
      {
        "value": 8,
        "weight": 0.07582650894752804
      },
      {
        "value": 64,
        "weight": 0.040238600748154885
      },
      {
        "value": 12,
        "weight": 0.0256799110302295
      },
      {
        "value": 24,
        "weight": 0.020018198362147403
      },
      {
        "value": 4,
        "weight": 0.015266403801435648
      },
      {
        "value": 48,
        "weight": 0.011930037407744412
      },
      {
        "value": 60,
        "weight": 0.009099181073703368
      },
      {
        "value": 28,
        "weight": 0.005257304620361944
      }
    ]
  },
  "linux": {
    "resolutions": [
      {
        "value": {
          "width": 1920,
          "height": 1080
        },
        "weight": 0.4297773427942256
      },
      {
        "value": {
          "width": 2560,
          "height": 1440
        },
        "weight": 0.1942745289943724
      },
      {
        "value": {
          "width": 3840,
          "height": 2160
        },
        "weight": 0.07633961340836799
      },
      {
        "value": {
          "width": 1280,
          "height": 800
        },
        "weight": 0.06936628333741131
      },
      {
        "value": {
          "width": 3440,
          "height": 1440
        },
        "weight": 0.0555419623195498
      },
      {
        "value": {
          "width": 1366,
          "height": 768
        },
        "weight": 0.04135062392953266
      },
      {
        "value": {
          "width": 1920,
          "height": 1200
        },
        "weight": 0.04122828480548079
      },
      {
        "value": {
          "width": 2560,
          "height": 1600
        },
        "weight": 0.019329581600195746
      },
      {
        "value": {
          "width": 2560,
          "height": 1080
        },
        "weight": 0.009542451676045999
      },
      {
        "value": {
          "width": 1600,
          "height": 900
        },
        "weight": 0.009175434303890383
      },
      {
        "value": {
          "width": 5120,
          "height": 1440
        },
        "weight": 0.00893075605578664
      },
      {
        "value": {
          "width": 2880,
          "height": 1800
        },
        "weight": 0.006116956202593589
      },
      {
        "value": {
          "width": 1280,
          "height": 720
        },
        "weight": 0.005749938830437973
      },
      {
        "value": {
          "width": 3072,
          "height": 1728
        },
        "weight": 0.005627599706386102
      },
      {
        "value": {
          "width": 1440,
          "height": 900
        },
        "weight": 0.005138243210178615
      },
      {
        "value": {
          "width": 1360,
          "height": 768
        },
        "weight": 0.004526547589919256
      },
      {
        "value": {
          "width": 1680,
          "height": 1050
        },
        "weight": 0.004281869341815512
      },
      {
        "value": {
          "width": 5120,
          "height": 2880
        },
        "weight": 0.003914851969659897
      },
      {
        "value": {
          "width": 3840,
          "height": 2400
        },
        "weight": 0.0035478345975042814
      },
      {
        "value": {
          "width": 3072,
          "height": 1920
        },
        "weight": 0.0031808172253486662
      },
      {
        "value": {
          "width": 2256,
          "height": 1504
        },
        "weight": 0.0030584781012967946
      }
    ],
    "cpuCores": [
      {
        "value": 4,
        "weight": 0.3393339333933394
      },
      {
        "value": 8,
        "weight": 0.2546254625462547
      },
      {
        "value": 6,
        "weight": 0.18961896189618968
      },
      {
        "value": 12,
        "weight": 0.051305130513051314
      },
      {
        "value": 16,
        "weight": 0.04840484048404842
      },
      {
        "value": 2,
        "weight": 0.04830483048304832
      },
      {
        "value": 10,
        "weight": 0.02830283028302831
      },
      {
        "value": 14,
        "weight": 0.018501850185018508
      },
      {
        "value": 24,
        "weight": 0.012601260126012604
      },
      {
        "value": 20,
        "weight": 0.007100710071007102
      },
      {
        "value": 5,
        "weight": 0.00040004000400040016
      },
      {
        "value": 18,
        "weight": 0.00040004000400040016
      },
      {
        "value": 32,
        "weight": 0.00040004000400040016
      },
      {
        "value": 1,
        "weight": 0.00020002000200020008
      },
      {
        "value": 3,
        "weight": 0.00020002000200020008
      },
      {
        "value": 28,
        "weight": 0.00010001000100010004
      },
      {
        "value": 36,
        "weight": 0.00010001000100010004
      },
      {
        "value": 64,
        "weight": 0.00010001000100010004
      }
    ],
    "ram": [
      {
        "value": 16,
        "weight": 0.45425608378683646
      },
      {
        "value": 32,
        "weight": 0.30270048259574905
      },
      {
        "value": 8,
        "weight": 0.06561248588150734
      },
      {
        "value": 64,
        "weight": 0.05010781394393675
      },
      {
        "value": 12,
        "weight": 0.03408974227333402
      },
      {
        "value": 60,
        "weight": 0.03018790430228976
      },
      {
        "value": 4,
        "weight": 0.021768148680562687
      },
      {
        "value": 24,
        "weight": 0.01796899065612486
      },
      {
        "value": 28,
        "weight": 0.012116233699558476
      },
      {
        "value": 48,
        "weight": 0.011192114180100627
      }
    ]
  }
};
