// Generated by scripts/build-locales.mjs. Do not edit by hand.
// Source catalogs:
// - Firefox: https://raw.githubusercontent.com/mozilla-firefox/firefox/main/intl/locale/language.properties
// - Chromium: https://raw.githubusercontent.com/chromium/chromium/main/ui/base/l10n/l10n_util.cc

export type BrowserLocaleTarget = "chromium" | "firefox";

export type BrowserLocaleOption = {
  readonly value: string;
  readonly label: string;
};

export type BrowserLocaleCatalogEntry = BrowserLocaleOption & {
  readonly targets: readonly BrowserLocaleTarget[];
};

export const localeCatalog = [
  {
    "value": "ab",
    "label": "Abkhazian [ab]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ach",
    "label": "Acoli [ach]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "aa",
    "label": "Afar [aa]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "af",
    "label": "Afrikaans [af]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ak",
    "label": "Akan [ak]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tw",
    "label": "Akan [tw]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sq",
    "label": "Albanian [sq]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "am",
    "label": "Amharic [am]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ar-DZ",
    "label": "Arabic (Algeria) [ar-DZ]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-BH",
    "label": "Arabic (Bahrain) [ar-BH]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-EG",
    "label": "Arabic (Egypt) [ar-EG]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-IQ",
    "label": "Arabic (Iraq) [ar-IQ]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-JO",
    "label": "Arabic (Jordan) [ar-JO]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-KW",
    "label": "Arabic (Kuwait) [ar-KW]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-LB",
    "label": "Arabic (Lebanon) [ar-LB]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-LY",
    "label": "Arabic (Libya) [ar-LY]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-MA",
    "label": "Arabic (Morocco) [ar-MA]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-OM",
    "label": "Arabic (Oman) [ar-OM]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-QA",
    "label": "Arabic (Qatar) [ar-QA]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-SA",
    "label": "Arabic (Saudi Arabia) [ar-SA]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-SY",
    "label": "Arabic (Syria) [ar-SY]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-TN",
    "label": "Arabic (Tunisia) [ar-TN]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-AE",
    "label": "Arabic (United Arab Emirates) [ar-AE]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar-YE",
    "label": "Arabic (Yemen) [ar-YE]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ar",
    "label": "Arabic [ar]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "an",
    "label": "Aragonese [an]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "hy",
    "label": "Armenian [hy]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "as",
    "label": "Assamese [as]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ast",
    "label": "Asturian [ast]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "av",
    "label": "Avaric [av]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ae",
    "label": "Avestan [ae]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ay",
    "label": "Aymara [ay]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "az",
    "label": "Azerbaijani (Latin) [az]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "bm",
    "label": "Bamanankan [bm]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "bn",
    "label": "Bangla [bn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ba",
    "label": "Bashkir [ba]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "eu",
    "label": "Basque [eu]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "be",
    "label": "Belarusian [be]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "bh",
    "label": "Bhojpuri [bh]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "bho",
    "label": "Bhojpuri [bho]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "bi",
    "label": "Bislama [bi]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "bs",
    "label": "Bosnian (Latin) [bs]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "br",
    "label": "Breton [br]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "bg",
    "label": "Bulgarian [bg]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "my",
    "label": "Burmese [my]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "cak",
    "label": "cak [cak]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ca-valencia",
    "label": "Catalan (Valencian) [ca-valencia]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ca",
    "label": "Catalan [ca]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ceb",
    "label": "Cebuano [ceb]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "ckb",
    "label": "Central Kurdish [ckb]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "ku",
    "label": "Central Kurdish [ku]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ch",
    "label": "Chamorro [ch]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ce",
    "label": "Chechen [ce]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "chr",
    "label": "Cherokee [chr]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "zh-CN",
    "label": "Chinese (Simplified) (China) [zh-CN]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "zh-SG",
    "label": "Chinese (Simplified) (Singapore) [zh-SG]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "zh",
    "label": "Chinese (Simplified) [zh]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "zh-HK",
    "label": "Chinese (Traditional) [zh-HK]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "zh-TW",
    "label": "Chinese (Traditional) [zh-TW]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "cu",
    "label": "Church Slavic [cu]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "cv",
    "label": "Chuvash [cv]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kw",
    "label": "Cornish [kw]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "co",
    "label": "Corsican [co]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "cr",
    "label": "Cree [cr]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "crh",
    "label": "Crimean Tatar [crh]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "hr",
    "label": "Croatian [hr]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "cs",
    "label": "Czech [cs]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "da",
    "label": "Danish [da]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "dv",
    "label": "Divehi [dv]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "doi",
    "label": "Dogri [doi]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "nl-BE",
    "label": "Dutch (Belgium) [nl-BE]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "nl",
    "label": "Dutch [nl]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "dz",
    "label": "Dzongkha [dz]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en-AU",
    "label": "English (Australia) [en-AU]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-BZ",
    "label": "English (Belize) [en-BZ]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en-CA",
    "label": "English (Canada) [en-CA]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-IN",
    "label": "English (India) [en-IN]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "en-IE",
    "label": "English (Ireland) [en-IE]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-JM",
    "label": "English (Jamaica) [en-JM]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en-NZ",
    "label": "English (New Zealand) [en-NZ]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-PH",
    "label": "English (Philippines) [en-PH]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en-ZA",
    "label": "English (South Africa) [en-ZA]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-TT",
    "label": "English (Trinidad & Tobago) [en-TT]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en-GB-oxendict",
    "label": "English (United Kingdom, Oxford English Dictionary spelling) [en-GB-oxendict]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "en-GB",
    "label": "English (United Kingdom) [en-GB]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-US",
    "label": "English (United States) [en-US]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "en-ZW",
    "label": "English (Zimbabwe) [en-ZW]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "en",
    "label": "English [en]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "eo",
    "label": "Esperanto [eo]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "et",
    "label": "Estonian [et]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ee",
    "label": "Ewe [ee]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fo",
    "label": "Faroese [fo]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fj",
    "label": "Fijian [fj]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fil",
    "label": "Filipino [fil]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "tl",
    "label": "Filipino [tl]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fi",
    "label": "Finnish [fi]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fr-BE",
    "label": "French (Belgium) [fr-BE]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fr-CA",
    "label": "French (Canada) [fr-CA]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fr-FR",
    "label": "French (France) [fr-FR]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fr-LU",
    "label": "French (Luxembourg) [fr-LU]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fr-MC",
    "label": "French (Monaco) [fr-MC]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fr-CH",
    "label": "French (Switzerland) [fr-CH]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fr",
    "label": "French [fr]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fy",
    "label": "Frisian [fy]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fur",
    "label": "Friulian [fur]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ff",
    "label": "Fulah [ff]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "gl",
    "label": "Galician [gl]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "lg",
    "label": "Ganda [lg]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ka",
    "label": "Georgian [ka]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "de-AT",
    "label": "German (Austria) [de-AT]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "de-DE",
    "label": "German (Germany) [de-DE]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "de-LI",
    "label": "German (Liechtenstein) [de-LI]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "de-LU",
    "label": "German (Luxembourg) [de-LU]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "de-CH",
    "label": "German (Switzerland) [de-CH]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "de",
    "label": "German [de]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "el",
    "label": "Greek [el]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "kl",
    "label": "Greenlandic [kl]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "gn",
    "label": "Guarani [gn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "gu",
    "label": "Gujarati [gu]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ht",
    "label": "Haitian Creole [ht]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ha",
    "label": "Hausa (Latin) [ha]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "haw",
    "label": "Hawaiian [haw]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "he",
    "label": "Hebrew [he]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "hz",
    "label": "Herero [hz]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "hil",
    "label": "Hiligaynon [hil]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "hi",
    "label": "Hindi [hi]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ho",
    "label": "Hiri Motu [ho]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "hmn",
    "label": "Hmong [hmn]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "hu",
    "label": "Hungarian [hu]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "is",
    "label": "Icelandic [is]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "io",
    "label": "Ido [io]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ig",
    "label": "Igbo [ig]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ilo",
    "label": "Iloko [ilo]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "id",
    "label": "Indonesian [id]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ia",
    "label": "Interlingua [ia]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ie",
    "label": "Interlingue [ie]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "iu",
    "label": "Inuktitut (Latin) [iu]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ik",
    "label": "Inupiaq [ik]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ga",
    "label": "Irish [ga]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "it-IT",
    "label": "Italian (Italy) [it-IT]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "it-CH",
    "label": "Italian (Switzerland) [it-CH]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "it",
    "label": "Italian [it]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ja",
    "label": "Japanese [ja]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "jv",
    "label": "Javanese [jv]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "kab",
    "label": "Kabyle [kab]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kn",
    "label": "Kannada [kn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "kr",
    "label": "Kanuri [kr]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ks",
    "label": "Kashmiri [ks]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "csb",
    "label": "Kashubian [csb]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kk",
    "label": "Kazakh [kk]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "km",
    "label": "Khmer [km]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ki",
    "label": "Kikuyu [ki]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "rw",
    "label": "Kinyarwanda [rw]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sw",
    "label": "Kiswahili [sw]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tlh",
    "label": "Klingon [tlh]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kv",
    "label": "Komi [kv]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kg",
    "label": "Kongo [kg]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "kok",
    "label": "Konkani [kok]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ko-KP",
    "label": "Korean (North Korea) [ko-KP]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ko-KR",
    "label": "Korean (South Korea) [ko-KR]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ko",
    "label": "Korean [ko]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "kri",
    "label": "Krio [kri]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "ky",
    "label": "Kyrgyz [ky]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "lo",
    "label": "Lao [lo]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ltg",
    "label": "Latgalian [ltg]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "la",
    "label": "Latin [la]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "lv",
    "label": "Latvian [lv]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "lij",
    "label": "Ligurian [lij]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "li",
    "label": "Limburgish [li]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ln",
    "label": "Lingala [ln]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "lt",
    "label": "Lithuanian [lt]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "dsb",
    "label": "Lower Sorbian [dsb]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "lu",
    "label": "Luba-Katanga [lu]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "lb",
    "label": "Luxembourgish [lb]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mk-MK",
    "label": "Macedonian (North Macedonia) [mk-MK]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "mk",
    "label": "Macedonian [mk]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mai",
    "label": "Maithili [mai]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mg",
    "label": "Malagasy [mg]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ms",
    "label": "Malay [ms]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ml",
    "label": "Malayalam [ml]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mt",
    "label": "Maltese [mt]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mni-Mtei",
    "label": "Manipuri (Meitei Mayek) [mni-Mtei]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "gv",
    "label": "Manx [gv]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "mi",
    "label": "Maori [mi]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mr",
    "label": "Marathi [mr]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "mh",
    "label": "Marshallese [mh]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "meh",
    "label": "meh [meh]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "mix",
    "label": "mix [mix]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "lus",
    "label": "Mizo [lus]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "mn",
    "label": "Mongolian (Cyrillic) [mn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "na",
    "label": "Nauru [na]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "nv",
    "label": "Navajo [nv]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ng",
    "label": "Ndonga [ng]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ne",
    "label": "Nepali [ne]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "nd",
    "label": "North Ndebele [nd]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "nb",
    "label": "Norwegian (Bokmal) [nb]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "no",
    "label": "Norwegian (Bokmal) [no]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "nn",
    "label": "Norwegian (Nynorsk) [nn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ny",
    "label": "Nyanja [ny]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "oc",
    "label": "Occitan [oc]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "or",
    "label": "Odia [or]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "oj",
    "label": "Ojibwa [oj]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "om",
    "label": "Oromo [om]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "os",
    "label": "Ossetian [os]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "pi",
    "label": "Pali [pi]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ps",
    "label": "Pashto [ps]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "fa-IR",
    "label": "Persian (Iran) [fa-IR]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "fa",
    "label": "Persian [fa]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "pl",
    "label": "Polish [pl]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "pt-BR",
    "label": "Portuguese (Brazil) [pt-BR]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "pt-PT",
    "label": "Portuguese (Portugal) [pt-PT]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "pt",
    "label": "Portuguese [pt]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "pa-IN",
    "label": "Punjabi (India) [pa-IN]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "pa-PK",
    "label": "Punjabi (Pakistan) [pa-PK]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "pa",
    "label": "Punjabi [pa]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "qu",
    "label": "Quechua [qu]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ro-MD",
    "label": "Romanian (Moldova) [ro-MD]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ro-RO",
    "label": "Romanian (Romania) [ro-RO]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "mo",
    "label": "Romanian [mo]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "ro",
    "label": "Romanian [ro]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "rm",
    "label": "Romansh [rm]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "rn",
    "label": "Rundi [rn]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ru-MD",
    "label": "Russian (Moldova) [ru-MD]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ru",
    "label": "Russian [ru]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sm",
    "label": "Samoan [sm]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sg",
    "label": "Sango [sg]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sa",
    "label": "Sanskrit [sa]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sat",
    "label": "Santali [sat]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sc",
    "label": "Sardinian [sc]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sco",
    "label": "Scots [sco]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "gd",
    "label": "Scottish Gaelic [gd]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sh",
    "label": "Serbian (Latin) [sh]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "sr",
    "label": "Serbian (Latin) [sr]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "nso",
    "label": "Sesotho sa Leboa [nso]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tn",
    "label": "Setswana [tn]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sn",
    "label": "Shona [sn]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "szl",
    "label": "Silesian [szl]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sd",
    "label": "Sindhi [sd]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "si",
    "label": "Sinhala [si]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "skr",
    "label": "skr [skr]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sk",
    "label": "Slovak [sk]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "sl",
    "label": "Slovenian [sl]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "so",
    "label": "Somali [so]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "son-ML",
    "label": "son (Mali) [son-ML]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "son",
    "label": "son [son]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "st",
    "label": "Sotho [st]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "nr",
    "label": "South Ndebele [nr]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-AR",
    "label": "Spanish (Argentina) [es-AR]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-BO",
    "label": "Spanish (Bolivia) [es-BO]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-CL",
    "label": "Spanish (Chile) [es-CL]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-CO",
    "label": "Spanish (Colombia) [es-CO]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-CR",
    "label": "Spanish (Costa Rica) [es-CR]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-DO",
    "label": "Spanish (Dominican Republic) [es-DO]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-EC",
    "label": "Spanish (Ecuador) [es-EC]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-SV",
    "label": "Spanish (El Salvador) [es-SV]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-GT",
    "label": "Spanish (Guatemala) [es-GT]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-HN",
    "label": "Spanish (Honduras) [es-HN]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-419",
    "label": "Spanish (Latin America) [es-419]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "es-MX",
    "label": "Spanish (Mexico) [es-MX]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-NI",
    "label": "Spanish (Nicaragua) [es-NI]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-PA",
    "label": "Spanish (Panama) [es-PA]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-PY",
    "label": "Spanish (Paraguay) [es-PY]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-PE",
    "label": "Spanish (Peru) [es-PE]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-PR",
    "label": "Spanish (Puerto Rico) [es-PR]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "es-ES",
    "label": "Spanish (Spain) [es-ES]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-US",
    "label": "Spanish (United States) [es-US]",
    "targets": [
      "chromium"
    ]
  },
  {
    "value": "es-UY",
    "label": "Spanish (Uruguay) [es-UY]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es-VE",
    "label": "Spanish (Venezuela) [es-VE]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "es",
    "label": "Spanish [es]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "su",
    "label": "Sundanese [su]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ss",
    "label": "Swati [ss]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sv-FI",
    "label": "Swedish (Finland) [sv-FI]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sv-SE",
    "label": "Swedish (Sweden) [sv-SE]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "sv",
    "label": "Swedish [sv]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ty",
    "label": "Tahitian [ty]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "tg",
    "label": "Tajik (Cyrillic) [tg]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ta",
    "label": "Tamil [ta]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tt",
    "label": "Tatar [tt]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "te",
    "label": "Telugu [te]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "th",
    "label": "Thai [th]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "bo",
    "label": "Tibetan [bo]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "tig",
    "label": "Tigre [tig]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ti",
    "label": "Tigrinya [ti]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "to",
    "label": "Tongan [to]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "trs",
    "label": "trs [trs]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ts",
    "label": "Tsonga [ts]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tr",
    "label": "Turkish [tr]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "tk",
    "label": "Turkmen [tk]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "uk",
    "label": "Ukrainian [uk]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "hsb",
    "label": "Upper Sorbian [hsb]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "ur",
    "label": "Urdu [ur]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ug",
    "label": "Uyghur [ug]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "uz",
    "label": "Uzbek (Latin) [uz]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ve",
    "label": "Venda [ve]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "vi",
    "label": "Vietnamese [vi]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "vo",
    "label": "Volapük [vo]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "wa",
    "label": "Walloon [wa]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "cy",
    "label": "Welsh [cy]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "wo",
    "label": "Wolof [wo]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "xh",
    "label": "Xhosa [xh]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "ii",
    "label": "Yi [ii]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "yi",
    "label": "Yiddish [yi]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "yo",
    "label": "Yoruba [yo]",
    "targets": [
      "firefox",
      "chromium"
    ]
  },
  {
    "value": "zam",
    "label": "zam [zam]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "za",
    "label": "Zhuang [za]",
    "targets": [
      "firefox"
    ]
  },
  {
    "value": "zu",
    "label": "Zulu [zu]",
    "targets": [
      "firefox",
      "chromium"
    ]
  }
] as const satisfies readonly BrowserLocaleCatalogEntry[];

export const localeOptionsByTarget = {
  "chromium": [
    {
      "value": "af",
      "label": "Afrikaans [af]"
    },
    {
      "value": "ak",
      "label": "Akan [ak]"
    },
    {
      "value": "tw",
      "label": "Akan [tw]"
    },
    {
      "value": "sq",
      "label": "Albanian [sq]"
    },
    {
      "value": "am",
      "label": "Amharic [am]"
    },
    {
      "value": "ar",
      "label": "Arabic [ar]"
    },
    {
      "value": "an",
      "label": "Aragonese [an]"
    },
    {
      "value": "hy",
      "label": "Armenian [hy]"
    },
    {
      "value": "as",
      "label": "Assamese [as]"
    },
    {
      "value": "ast",
      "label": "Asturian [ast]"
    },
    {
      "value": "ay",
      "label": "Aymara [ay]"
    },
    {
      "value": "az",
      "label": "Azerbaijani (Latin) [az]"
    },
    {
      "value": "bm",
      "label": "Bamanankan [bm]"
    },
    {
      "value": "bn",
      "label": "Bangla [bn]"
    },
    {
      "value": "eu",
      "label": "Basque [eu]"
    },
    {
      "value": "be",
      "label": "Belarusian [be]"
    },
    {
      "value": "bho",
      "label": "Bhojpuri [bho]"
    },
    {
      "value": "bs",
      "label": "Bosnian (Latin) [bs]"
    },
    {
      "value": "br",
      "label": "Breton [br]"
    },
    {
      "value": "bg",
      "label": "Bulgarian [bg]"
    },
    {
      "value": "my",
      "label": "Burmese [my]"
    },
    {
      "value": "ca",
      "label": "Catalan [ca]"
    },
    {
      "value": "ceb",
      "label": "Cebuano [ceb]"
    },
    {
      "value": "ckb",
      "label": "Central Kurdish [ckb]"
    },
    {
      "value": "ku",
      "label": "Central Kurdish [ku]"
    },
    {
      "value": "chr",
      "label": "Cherokee [chr]"
    },
    {
      "value": "zh-CN",
      "label": "Chinese (Simplified) (China) [zh-CN]"
    },
    {
      "value": "zh",
      "label": "Chinese (Simplified) [zh]"
    },
    {
      "value": "zh-HK",
      "label": "Chinese (Traditional) [zh-HK]"
    },
    {
      "value": "zh-TW",
      "label": "Chinese (Traditional) [zh-TW]"
    },
    {
      "value": "co",
      "label": "Corsican [co]"
    },
    {
      "value": "hr",
      "label": "Croatian [hr]"
    },
    {
      "value": "cs",
      "label": "Czech [cs]"
    },
    {
      "value": "da",
      "label": "Danish [da]"
    },
    {
      "value": "dv",
      "label": "Divehi [dv]"
    },
    {
      "value": "doi",
      "label": "Dogri [doi]"
    },
    {
      "value": "nl",
      "label": "Dutch [nl]"
    },
    {
      "value": "en-AU",
      "label": "English (Australia) [en-AU]"
    },
    {
      "value": "en-CA",
      "label": "English (Canada) [en-CA]"
    },
    {
      "value": "en-IN",
      "label": "English (India) [en-IN]"
    },
    {
      "value": "en-IE",
      "label": "English (Ireland) [en-IE]"
    },
    {
      "value": "en-NZ",
      "label": "English (New Zealand) [en-NZ]"
    },
    {
      "value": "en-ZA",
      "label": "English (South Africa) [en-ZA]"
    },
    {
      "value": "en-GB-oxendict",
      "label": "English (United Kingdom, Oxford English Dictionary spelling) [en-GB-oxendict]"
    },
    {
      "value": "en-GB",
      "label": "English (United Kingdom) [en-GB]"
    },
    {
      "value": "en-US",
      "label": "English (United States) [en-US]"
    },
    {
      "value": "en",
      "label": "English [en]"
    },
    {
      "value": "eo",
      "label": "Esperanto [eo]"
    },
    {
      "value": "et",
      "label": "Estonian [et]"
    },
    {
      "value": "ee",
      "label": "Ewe [ee]"
    },
    {
      "value": "fo",
      "label": "Faroese [fo]"
    },
    {
      "value": "fil",
      "label": "Filipino [fil]"
    },
    {
      "value": "fi",
      "label": "Finnish [fi]"
    },
    {
      "value": "fr-CA",
      "label": "French (Canada) [fr-CA]"
    },
    {
      "value": "fr-FR",
      "label": "French (France) [fr-FR]"
    },
    {
      "value": "fr-CH",
      "label": "French (Switzerland) [fr-CH]"
    },
    {
      "value": "fr",
      "label": "French [fr]"
    },
    {
      "value": "fy",
      "label": "Frisian [fy]"
    },
    {
      "value": "gl",
      "label": "Galician [gl]"
    },
    {
      "value": "lg",
      "label": "Ganda [lg]"
    },
    {
      "value": "ka",
      "label": "Georgian [ka]"
    },
    {
      "value": "de-AT",
      "label": "German (Austria) [de-AT]"
    },
    {
      "value": "de-DE",
      "label": "German (Germany) [de-DE]"
    },
    {
      "value": "de-LI",
      "label": "German (Liechtenstein) [de-LI]"
    },
    {
      "value": "de-CH",
      "label": "German (Switzerland) [de-CH]"
    },
    {
      "value": "de",
      "label": "German [de]"
    },
    {
      "value": "el",
      "label": "Greek [el]"
    },
    {
      "value": "gn",
      "label": "Guarani [gn]"
    },
    {
      "value": "gu",
      "label": "Gujarati [gu]"
    },
    {
      "value": "ht",
      "label": "Haitian Creole [ht]"
    },
    {
      "value": "ha",
      "label": "Hausa (Latin) [ha]"
    },
    {
      "value": "haw",
      "label": "Hawaiian [haw]"
    },
    {
      "value": "he",
      "label": "Hebrew [he]"
    },
    {
      "value": "hi",
      "label": "Hindi [hi]"
    },
    {
      "value": "hmn",
      "label": "Hmong [hmn]"
    },
    {
      "value": "hu",
      "label": "Hungarian [hu]"
    },
    {
      "value": "is",
      "label": "Icelandic [is]"
    },
    {
      "value": "ig",
      "label": "Igbo [ig]"
    },
    {
      "value": "ilo",
      "label": "Iloko [ilo]"
    },
    {
      "value": "id",
      "label": "Indonesian [id]"
    },
    {
      "value": "ia",
      "label": "Interlingua [ia]"
    },
    {
      "value": "ga",
      "label": "Irish [ga]"
    },
    {
      "value": "it-IT",
      "label": "Italian (Italy) [it-IT]"
    },
    {
      "value": "it-CH",
      "label": "Italian (Switzerland) [it-CH]"
    },
    {
      "value": "it",
      "label": "Italian [it]"
    },
    {
      "value": "ja",
      "label": "Japanese [ja]"
    },
    {
      "value": "jv",
      "label": "Javanese [jv]"
    },
    {
      "value": "kn",
      "label": "Kannada [kn]"
    },
    {
      "value": "kk",
      "label": "Kazakh [kk]"
    },
    {
      "value": "km",
      "label": "Khmer [km]"
    },
    {
      "value": "rw",
      "label": "Kinyarwanda [rw]"
    },
    {
      "value": "sw",
      "label": "Kiswahili [sw]"
    },
    {
      "value": "kok",
      "label": "Konkani [kok]"
    },
    {
      "value": "ko",
      "label": "Korean [ko]"
    },
    {
      "value": "kri",
      "label": "Krio [kri]"
    },
    {
      "value": "ky",
      "label": "Kyrgyz [ky]"
    },
    {
      "value": "lo",
      "label": "Lao [lo]"
    },
    {
      "value": "la",
      "label": "Latin [la]"
    },
    {
      "value": "lv",
      "label": "Latvian [lv]"
    },
    {
      "value": "ln",
      "label": "Lingala [ln]"
    },
    {
      "value": "lt",
      "label": "Lithuanian [lt]"
    },
    {
      "value": "lb",
      "label": "Luxembourgish [lb]"
    },
    {
      "value": "mk",
      "label": "Macedonian [mk]"
    },
    {
      "value": "mai",
      "label": "Maithili [mai]"
    },
    {
      "value": "mg",
      "label": "Malagasy [mg]"
    },
    {
      "value": "ms",
      "label": "Malay [ms]"
    },
    {
      "value": "ml",
      "label": "Malayalam [ml]"
    },
    {
      "value": "mt",
      "label": "Maltese [mt]"
    },
    {
      "value": "mni-Mtei",
      "label": "Manipuri (Meitei Mayek) [mni-Mtei]"
    },
    {
      "value": "mi",
      "label": "Maori [mi]"
    },
    {
      "value": "mr",
      "label": "Marathi [mr]"
    },
    {
      "value": "lus",
      "label": "Mizo [lus]"
    },
    {
      "value": "mn",
      "label": "Mongolian (Cyrillic) [mn]"
    },
    {
      "value": "ne",
      "label": "Nepali [ne]"
    },
    {
      "value": "nb",
      "label": "Norwegian (Bokmal) [nb]"
    },
    {
      "value": "no",
      "label": "Norwegian (Bokmal) [no]"
    },
    {
      "value": "nn",
      "label": "Norwegian (Nynorsk) [nn]"
    },
    {
      "value": "ny",
      "label": "Nyanja [ny]"
    },
    {
      "value": "oc",
      "label": "Occitan [oc]"
    },
    {
      "value": "or",
      "label": "Odia [or]"
    },
    {
      "value": "om",
      "label": "Oromo [om]"
    },
    {
      "value": "ps",
      "label": "Pashto [ps]"
    },
    {
      "value": "fa",
      "label": "Persian [fa]"
    },
    {
      "value": "pl",
      "label": "Polish [pl]"
    },
    {
      "value": "pt-BR",
      "label": "Portuguese (Brazil) [pt-BR]"
    },
    {
      "value": "pt-PT",
      "label": "Portuguese (Portugal) [pt-PT]"
    },
    {
      "value": "pt",
      "label": "Portuguese [pt]"
    },
    {
      "value": "pa",
      "label": "Punjabi [pa]"
    },
    {
      "value": "qu",
      "label": "Quechua [qu]"
    },
    {
      "value": "mo",
      "label": "Romanian [mo]"
    },
    {
      "value": "ro",
      "label": "Romanian [ro]"
    },
    {
      "value": "rm",
      "label": "Romansh [rm]"
    },
    {
      "value": "ru",
      "label": "Russian [ru]"
    },
    {
      "value": "sm",
      "label": "Samoan [sm]"
    },
    {
      "value": "sa",
      "label": "Sanskrit [sa]"
    },
    {
      "value": "gd",
      "label": "Scottish Gaelic [gd]"
    },
    {
      "value": "sh",
      "label": "Serbian (Latin) [sh]"
    },
    {
      "value": "sr",
      "label": "Serbian (Latin) [sr]"
    },
    {
      "value": "nso",
      "label": "Sesotho sa Leboa [nso]"
    },
    {
      "value": "tn",
      "label": "Setswana [tn]"
    },
    {
      "value": "sn",
      "label": "Shona [sn]"
    },
    {
      "value": "sd",
      "label": "Sindhi [sd]"
    },
    {
      "value": "si",
      "label": "Sinhala [si]"
    },
    {
      "value": "sk",
      "label": "Slovak [sk]"
    },
    {
      "value": "sl",
      "label": "Slovenian [sl]"
    },
    {
      "value": "so",
      "label": "Somali [so]"
    },
    {
      "value": "st",
      "label": "Sotho [st]"
    },
    {
      "value": "es-AR",
      "label": "Spanish (Argentina) [es-AR]"
    },
    {
      "value": "es-CL",
      "label": "Spanish (Chile) [es-CL]"
    },
    {
      "value": "es-CO",
      "label": "Spanish (Colombia) [es-CO]"
    },
    {
      "value": "es-CR",
      "label": "Spanish (Costa Rica) [es-CR]"
    },
    {
      "value": "es-HN",
      "label": "Spanish (Honduras) [es-HN]"
    },
    {
      "value": "es-419",
      "label": "Spanish (Latin America) [es-419]"
    },
    {
      "value": "es-MX",
      "label": "Spanish (Mexico) [es-MX]"
    },
    {
      "value": "es-PE",
      "label": "Spanish (Peru) [es-PE]"
    },
    {
      "value": "es-ES",
      "label": "Spanish (Spain) [es-ES]"
    },
    {
      "value": "es-US",
      "label": "Spanish (United States) [es-US]"
    },
    {
      "value": "es-UY",
      "label": "Spanish (Uruguay) [es-UY]"
    },
    {
      "value": "es-VE",
      "label": "Spanish (Venezuela) [es-VE]"
    },
    {
      "value": "es",
      "label": "Spanish [es]"
    },
    {
      "value": "su",
      "label": "Sundanese [su]"
    },
    {
      "value": "sv",
      "label": "Swedish [sv]"
    },
    {
      "value": "tg",
      "label": "Tajik (Cyrillic) [tg]"
    },
    {
      "value": "ta",
      "label": "Tamil [ta]"
    },
    {
      "value": "tt",
      "label": "Tatar [tt]"
    },
    {
      "value": "te",
      "label": "Telugu [te]"
    },
    {
      "value": "th",
      "label": "Thai [th]"
    },
    {
      "value": "ti",
      "label": "Tigrinya [ti]"
    },
    {
      "value": "to",
      "label": "Tongan [to]"
    },
    {
      "value": "ts",
      "label": "Tsonga [ts]"
    },
    {
      "value": "tr",
      "label": "Turkish [tr]"
    },
    {
      "value": "tk",
      "label": "Turkmen [tk]"
    },
    {
      "value": "uk",
      "label": "Ukrainian [uk]"
    },
    {
      "value": "ur",
      "label": "Urdu [ur]"
    },
    {
      "value": "ug",
      "label": "Uyghur [ug]"
    },
    {
      "value": "uz",
      "label": "Uzbek (Latin) [uz]"
    },
    {
      "value": "vi",
      "label": "Vietnamese [vi]"
    },
    {
      "value": "wa",
      "label": "Walloon [wa]"
    },
    {
      "value": "cy",
      "label": "Welsh [cy]"
    },
    {
      "value": "wo",
      "label": "Wolof [wo]"
    },
    {
      "value": "xh",
      "label": "Xhosa [xh]"
    },
    {
      "value": "yi",
      "label": "Yiddish [yi]"
    },
    {
      "value": "yo",
      "label": "Yoruba [yo]"
    },
    {
      "value": "zu",
      "label": "Zulu [zu]"
    }
  ],
  "firefox": [
    {
      "value": "ab",
      "label": "Abkhazian [ab]"
    },
    {
      "value": "ach",
      "label": "Acoli [ach]"
    },
    {
      "value": "aa",
      "label": "Afar [aa]"
    },
    {
      "value": "af",
      "label": "Afrikaans [af]"
    },
    {
      "value": "ak",
      "label": "Akan [ak]"
    },
    {
      "value": "tw",
      "label": "Akan [tw]"
    },
    {
      "value": "sq",
      "label": "Albanian [sq]"
    },
    {
      "value": "am",
      "label": "Amharic [am]"
    },
    {
      "value": "ar-DZ",
      "label": "Arabic (Algeria) [ar-DZ]"
    },
    {
      "value": "ar-BH",
      "label": "Arabic (Bahrain) [ar-BH]"
    },
    {
      "value": "ar-EG",
      "label": "Arabic (Egypt) [ar-EG]"
    },
    {
      "value": "ar-IQ",
      "label": "Arabic (Iraq) [ar-IQ]"
    },
    {
      "value": "ar-JO",
      "label": "Arabic (Jordan) [ar-JO]"
    },
    {
      "value": "ar-KW",
      "label": "Arabic (Kuwait) [ar-KW]"
    },
    {
      "value": "ar-LB",
      "label": "Arabic (Lebanon) [ar-LB]"
    },
    {
      "value": "ar-LY",
      "label": "Arabic (Libya) [ar-LY]"
    },
    {
      "value": "ar-MA",
      "label": "Arabic (Morocco) [ar-MA]"
    },
    {
      "value": "ar-OM",
      "label": "Arabic (Oman) [ar-OM]"
    },
    {
      "value": "ar-QA",
      "label": "Arabic (Qatar) [ar-QA]"
    },
    {
      "value": "ar-SA",
      "label": "Arabic (Saudi Arabia) [ar-SA]"
    },
    {
      "value": "ar-SY",
      "label": "Arabic (Syria) [ar-SY]"
    },
    {
      "value": "ar-TN",
      "label": "Arabic (Tunisia) [ar-TN]"
    },
    {
      "value": "ar-AE",
      "label": "Arabic (United Arab Emirates) [ar-AE]"
    },
    {
      "value": "ar-YE",
      "label": "Arabic (Yemen) [ar-YE]"
    },
    {
      "value": "ar",
      "label": "Arabic [ar]"
    },
    {
      "value": "an",
      "label": "Aragonese [an]"
    },
    {
      "value": "hy",
      "label": "Armenian [hy]"
    },
    {
      "value": "as",
      "label": "Assamese [as]"
    },
    {
      "value": "ast",
      "label": "Asturian [ast]"
    },
    {
      "value": "av",
      "label": "Avaric [av]"
    },
    {
      "value": "ae",
      "label": "Avestan [ae]"
    },
    {
      "value": "ay",
      "label": "Aymara [ay]"
    },
    {
      "value": "az",
      "label": "Azerbaijani (Latin) [az]"
    },
    {
      "value": "bm",
      "label": "Bamanankan [bm]"
    },
    {
      "value": "bn",
      "label": "Bangla [bn]"
    },
    {
      "value": "ba",
      "label": "Bashkir [ba]"
    },
    {
      "value": "eu",
      "label": "Basque [eu]"
    },
    {
      "value": "be",
      "label": "Belarusian [be]"
    },
    {
      "value": "bh",
      "label": "Bhojpuri [bh]"
    },
    {
      "value": "bi",
      "label": "Bislama [bi]"
    },
    {
      "value": "bs",
      "label": "Bosnian (Latin) [bs]"
    },
    {
      "value": "br",
      "label": "Breton [br]"
    },
    {
      "value": "bg",
      "label": "Bulgarian [bg]"
    },
    {
      "value": "my",
      "label": "Burmese [my]"
    },
    {
      "value": "cak",
      "label": "cak [cak]"
    },
    {
      "value": "ca-valencia",
      "label": "Catalan (Valencian) [ca-valencia]"
    },
    {
      "value": "ca",
      "label": "Catalan [ca]"
    },
    {
      "value": "ku",
      "label": "Central Kurdish [ku]"
    },
    {
      "value": "ch",
      "label": "Chamorro [ch]"
    },
    {
      "value": "ce",
      "label": "Chechen [ce]"
    },
    {
      "value": "zh-CN",
      "label": "Chinese (Simplified) (China) [zh-CN]"
    },
    {
      "value": "zh-SG",
      "label": "Chinese (Simplified) (Singapore) [zh-SG]"
    },
    {
      "value": "zh",
      "label": "Chinese (Simplified) [zh]"
    },
    {
      "value": "zh-HK",
      "label": "Chinese (Traditional) [zh-HK]"
    },
    {
      "value": "zh-TW",
      "label": "Chinese (Traditional) [zh-TW]"
    },
    {
      "value": "cu",
      "label": "Church Slavic [cu]"
    },
    {
      "value": "cv",
      "label": "Chuvash [cv]"
    },
    {
      "value": "kw",
      "label": "Cornish [kw]"
    },
    {
      "value": "co",
      "label": "Corsican [co]"
    },
    {
      "value": "cr",
      "label": "Cree [cr]"
    },
    {
      "value": "crh",
      "label": "Crimean Tatar [crh]"
    },
    {
      "value": "hr",
      "label": "Croatian [hr]"
    },
    {
      "value": "cs",
      "label": "Czech [cs]"
    },
    {
      "value": "da",
      "label": "Danish [da]"
    },
    {
      "value": "dv",
      "label": "Divehi [dv]"
    },
    {
      "value": "nl-BE",
      "label": "Dutch (Belgium) [nl-BE]"
    },
    {
      "value": "nl",
      "label": "Dutch [nl]"
    },
    {
      "value": "dz",
      "label": "Dzongkha [dz]"
    },
    {
      "value": "en-AU",
      "label": "English (Australia) [en-AU]"
    },
    {
      "value": "en-BZ",
      "label": "English (Belize) [en-BZ]"
    },
    {
      "value": "en-CA",
      "label": "English (Canada) [en-CA]"
    },
    {
      "value": "en-IE",
      "label": "English (Ireland) [en-IE]"
    },
    {
      "value": "en-JM",
      "label": "English (Jamaica) [en-JM]"
    },
    {
      "value": "en-NZ",
      "label": "English (New Zealand) [en-NZ]"
    },
    {
      "value": "en-PH",
      "label": "English (Philippines) [en-PH]"
    },
    {
      "value": "en-ZA",
      "label": "English (South Africa) [en-ZA]"
    },
    {
      "value": "en-TT",
      "label": "English (Trinidad & Tobago) [en-TT]"
    },
    {
      "value": "en-GB",
      "label": "English (United Kingdom) [en-GB]"
    },
    {
      "value": "en-US",
      "label": "English (United States) [en-US]"
    },
    {
      "value": "en-ZW",
      "label": "English (Zimbabwe) [en-ZW]"
    },
    {
      "value": "en",
      "label": "English [en]"
    },
    {
      "value": "eo",
      "label": "Esperanto [eo]"
    },
    {
      "value": "et",
      "label": "Estonian [et]"
    },
    {
      "value": "ee",
      "label": "Ewe [ee]"
    },
    {
      "value": "fo",
      "label": "Faroese [fo]"
    },
    {
      "value": "fj",
      "label": "Fijian [fj]"
    },
    {
      "value": "tl",
      "label": "Filipino [tl]"
    },
    {
      "value": "fi",
      "label": "Finnish [fi]"
    },
    {
      "value": "fr-BE",
      "label": "French (Belgium) [fr-BE]"
    },
    {
      "value": "fr-CA",
      "label": "French (Canada) [fr-CA]"
    },
    {
      "value": "fr-FR",
      "label": "French (France) [fr-FR]"
    },
    {
      "value": "fr-LU",
      "label": "French (Luxembourg) [fr-LU]"
    },
    {
      "value": "fr-MC",
      "label": "French (Monaco) [fr-MC]"
    },
    {
      "value": "fr-CH",
      "label": "French (Switzerland) [fr-CH]"
    },
    {
      "value": "fr",
      "label": "French [fr]"
    },
    {
      "value": "fy",
      "label": "Frisian [fy]"
    },
    {
      "value": "fur",
      "label": "Friulian [fur]"
    },
    {
      "value": "ff",
      "label": "Fulah [ff]"
    },
    {
      "value": "gl",
      "label": "Galician [gl]"
    },
    {
      "value": "lg",
      "label": "Ganda [lg]"
    },
    {
      "value": "ka",
      "label": "Georgian [ka]"
    },
    {
      "value": "de-AT",
      "label": "German (Austria) [de-AT]"
    },
    {
      "value": "de-DE",
      "label": "German (Germany) [de-DE]"
    },
    {
      "value": "de-LI",
      "label": "German (Liechtenstein) [de-LI]"
    },
    {
      "value": "de-LU",
      "label": "German (Luxembourg) [de-LU]"
    },
    {
      "value": "de-CH",
      "label": "German (Switzerland) [de-CH]"
    },
    {
      "value": "de",
      "label": "German [de]"
    },
    {
      "value": "el",
      "label": "Greek [el]"
    },
    {
      "value": "kl",
      "label": "Greenlandic [kl]"
    },
    {
      "value": "gn",
      "label": "Guarani [gn]"
    },
    {
      "value": "gu",
      "label": "Gujarati [gu]"
    },
    {
      "value": "ht",
      "label": "Haitian Creole [ht]"
    },
    {
      "value": "ha",
      "label": "Hausa (Latin) [ha]"
    },
    {
      "value": "haw",
      "label": "Hawaiian [haw]"
    },
    {
      "value": "he",
      "label": "Hebrew [he]"
    },
    {
      "value": "hz",
      "label": "Herero [hz]"
    },
    {
      "value": "hil",
      "label": "Hiligaynon [hil]"
    },
    {
      "value": "hi",
      "label": "Hindi [hi]"
    },
    {
      "value": "ho",
      "label": "Hiri Motu [ho]"
    },
    {
      "value": "hu",
      "label": "Hungarian [hu]"
    },
    {
      "value": "is",
      "label": "Icelandic [is]"
    },
    {
      "value": "io",
      "label": "Ido [io]"
    },
    {
      "value": "ig",
      "label": "Igbo [ig]"
    },
    {
      "value": "id",
      "label": "Indonesian [id]"
    },
    {
      "value": "ia",
      "label": "Interlingua [ia]"
    },
    {
      "value": "ie",
      "label": "Interlingue [ie]"
    },
    {
      "value": "iu",
      "label": "Inuktitut (Latin) [iu]"
    },
    {
      "value": "ik",
      "label": "Inupiaq [ik]"
    },
    {
      "value": "ga",
      "label": "Irish [ga]"
    },
    {
      "value": "it-CH",
      "label": "Italian (Switzerland) [it-CH]"
    },
    {
      "value": "it",
      "label": "Italian [it]"
    },
    {
      "value": "ja",
      "label": "Japanese [ja]"
    },
    {
      "value": "jv",
      "label": "Javanese [jv]"
    },
    {
      "value": "kab",
      "label": "Kabyle [kab]"
    },
    {
      "value": "kn",
      "label": "Kannada [kn]"
    },
    {
      "value": "kr",
      "label": "Kanuri [kr]"
    },
    {
      "value": "ks",
      "label": "Kashmiri [ks]"
    },
    {
      "value": "csb",
      "label": "Kashubian [csb]"
    },
    {
      "value": "kk",
      "label": "Kazakh [kk]"
    },
    {
      "value": "km",
      "label": "Khmer [km]"
    },
    {
      "value": "ki",
      "label": "Kikuyu [ki]"
    },
    {
      "value": "rw",
      "label": "Kinyarwanda [rw]"
    },
    {
      "value": "sw",
      "label": "Kiswahili [sw]"
    },
    {
      "value": "tlh",
      "label": "Klingon [tlh]"
    },
    {
      "value": "kv",
      "label": "Komi [kv]"
    },
    {
      "value": "kg",
      "label": "Kongo [kg]"
    },
    {
      "value": "kok",
      "label": "Konkani [kok]"
    },
    {
      "value": "ko-KP",
      "label": "Korean (North Korea) [ko-KP]"
    },
    {
      "value": "ko-KR",
      "label": "Korean (South Korea) [ko-KR]"
    },
    {
      "value": "ko",
      "label": "Korean [ko]"
    },
    {
      "value": "ky",
      "label": "Kyrgyz [ky]"
    },
    {
      "value": "lo",
      "label": "Lao [lo]"
    },
    {
      "value": "ltg",
      "label": "Latgalian [ltg]"
    },
    {
      "value": "la",
      "label": "Latin [la]"
    },
    {
      "value": "lv",
      "label": "Latvian [lv]"
    },
    {
      "value": "lij",
      "label": "Ligurian [lij]"
    },
    {
      "value": "li",
      "label": "Limburgish [li]"
    },
    {
      "value": "ln",
      "label": "Lingala [ln]"
    },
    {
      "value": "lt",
      "label": "Lithuanian [lt]"
    },
    {
      "value": "dsb",
      "label": "Lower Sorbian [dsb]"
    },
    {
      "value": "lu",
      "label": "Luba-Katanga [lu]"
    },
    {
      "value": "lb",
      "label": "Luxembourgish [lb]"
    },
    {
      "value": "mk-MK",
      "label": "Macedonian (North Macedonia) [mk-MK]"
    },
    {
      "value": "mk",
      "label": "Macedonian [mk]"
    },
    {
      "value": "mai",
      "label": "Maithili [mai]"
    },
    {
      "value": "mg",
      "label": "Malagasy [mg]"
    },
    {
      "value": "ms",
      "label": "Malay [ms]"
    },
    {
      "value": "ml",
      "label": "Malayalam [ml]"
    },
    {
      "value": "mt",
      "label": "Maltese [mt]"
    },
    {
      "value": "gv",
      "label": "Manx [gv]"
    },
    {
      "value": "mi",
      "label": "Maori [mi]"
    },
    {
      "value": "mr",
      "label": "Marathi [mr]"
    },
    {
      "value": "mh",
      "label": "Marshallese [mh]"
    },
    {
      "value": "meh",
      "label": "meh [meh]"
    },
    {
      "value": "mix",
      "label": "mix [mix]"
    },
    {
      "value": "mn",
      "label": "Mongolian (Cyrillic) [mn]"
    },
    {
      "value": "na",
      "label": "Nauru [na]"
    },
    {
      "value": "nv",
      "label": "Navajo [nv]"
    },
    {
      "value": "ng",
      "label": "Ndonga [ng]"
    },
    {
      "value": "ne",
      "label": "Nepali [ne]"
    },
    {
      "value": "nd",
      "label": "North Ndebele [nd]"
    },
    {
      "value": "nb",
      "label": "Norwegian (Bokmal) [nb]"
    },
    {
      "value": "no",
      "label": "Norwegian (Bokmal) [no]"
    },
    {
      "value": "nn",
      "label": "Norwegian (Nynorsk) [nn]"
    },
    {
      "value": "ny",
      "label": "Nyanja [ny]"
    },
    {
      "value": "oc",
      "label": "Occitan [oc]"
    },
    {
      "value": "or",
      "label": "Odia [or]"
    },
    {
      "value": "oj",
      "label": "Ojibwa [oj]"
    },
    {
      "value": "om",
      "label": "Oromo [om]"
    },
    {
      "value": "os",
      "label": "Ossetian [os]"
    },
    {
      "value": "pi",
      "label": "Pali [pi]"
    },
    {
      "value": "ps",
      "label": "Pashto [ps]"
    },
    {
      "value": "fa-IR",
      "label": "Persian (Iran) [fa-IR]"
    },
    {
      "value": "fa",
      "label": "Persian [fa]"
    },
    {
      "value": "pl",
      "label": "Polish [pl]"
    },
    {
      "value": "pt-BR",
      "label": "Portuguese (Brazil) [pt-BR]"
    },
    {
      "value": "pt-PT",
      "label": "Portuguese (Portugal) [pt-PT]"
    },
    {
      "value": "pt",
      "label": "Portuguese [pt]"
    },
    {
      "value": "pa-IN",
      "label": "Punjabi (India) [pa-IN]"
    },
    {
      "value": "pa-PK",
      "label": "Punjabi (Pakistan) [pa-PK]"
    },
    {
      "value": "pa",
      "label": "Punjabi [pa]"
    },
    {
      "value": "qu",
      "label": "Quechua [qu]"
    },
    {
      "value": "ro-MD",
      "label": "Romanian (Moldova) [ro-MD]"
    },
    {
      "value": "ro-RO",
      "label": "Romanian (Romania) [ro-RO]"
    },
    {
      "value": "ro",
      "label": "Romanian [ro]"
    },
    {
      "value": "rm",
      "label": "Romansh [rm]"
    },
    {
      "value": "rn",
      "label": "Rundi [rn]"
    },
    {
      "value": "ru-MD",
      "label": "Russian (Moldova) [ru-MD]"
    },
    {
      "value": "ru",
      "label": "Russian [ru]"
    },
    {
      "value": "sm",
      "label": "Samoan [sm]"
    },
    {
      "value": "sg",
      "label": "Sango [sg]"
    },
    {
      "value": "sa",
      "label": "Sanskrit [sa]"
    },
    {
      "value": "sat",
      "label": "Santali [sat]"
    },
    {
      "value": "sc",
      "label": "Sardinian [sc]"
    },
    {
      "value": "sco",
      "label": "Scots [sco]"
    },
    {
      "value": "gd",
      "label": "Scottish Gaelic [gd]"
    },
    {
      "value": "sr",
      "label": "Serbian (Latin) [sr]"
    },
    {
      "value": "nso",
      "label": "Sesotho sa Leboa [nso]"
    },
    {
      "value": "tn",
      "label": "Setswana [tn]"
    },
    {
      "value": "szl",
      "label": "Silesian [szl]"
    },
    {
      "value": "sd",
      "label": "Sindhi [sd]"
    },
    {
      "value": "si",
      "label": "Sinhala [si]"
    },
    {
      "value": "skr",
      "label": "skr [skr]"
    },
    {
      "value": "sk",
      "label": "Slovak [sk]"
    },
    {
      "value": "sl",
      "label": "Slovenian [sl]"
    },
    {
      "value": "so",
      "label": "Somali [so]"
    },
    {
      "value": "son-ML",
      "label": "son (Mali) [son-ML]"
    },
    {
      "value": "son",
      "label": "son [son]"
    },
    {
      "value": "st",
      "label": "Sotho [st]"
    },
    {
      "value": "nr",
      "label": "South Ndebele [nr]"
    },
    {
      "value": "es-AR",
      "label": "Spanish (Argentina) [es-AR]"
    },
    {
      "value": "es-BO",
      "label": "Spanish (Bolivia) [es-BO]"
    },
    {
      "value": "es-CL",
      "label": "Spanish (Chile) [es-CL]"
    },
    {
      "value": "es-CO",
      "label": "Spanish (Colombia) [es-CO]"
    },
    {
      "value": "es-CR",
      "label": "Spanish (Costa Rica) [es-CR]"
    },
    {
      "value": "es-DO",
      "label": "Spanish (Dominican Republic) [es-DO]"
    },
    {
      "value": "es-EC",
      "label": "Spanish (Ecuador) [es-EC]"
    },
    {
      "value": "es-SV",
      "label": "Spanish (El Salvador) [es-SV]"
    },
    {
      "value": "es-GT",
      "label": "Spanish (Guatemala) [es-GT]"
    },
    {
      "value": "es-HN",
      "label": "Spanish (Honduras) [es-HN]"
    },
    {
      "value": "es-MX",
      "label": "Spanish (Mexico) [es-MX]"
    },
    {
      "value": "es-NI",
      "label": "Spanish (Nicaragua) [es-NI]"
    },
    {
      "value": "es-PA",
      "label": "Spanish (Panama) [es-PA]"
    },
    {
      "value": "es-PY",
      "label": "Spanish (Paraguay) [es-PY]"
    },
    {
      "value": "es-PE",
      "label": "Spanish (Peru) [es-PE]"
    },
    {
      "value": "es-PR",
      "label": "Spanish (Puerto Rico) [es-PR]"
    },
    {
      "value": "es-ES",
      "label": "Spanish (Spain) [es-ES]"
    },
    {
      "value": "es-UY",
      "label": "Spanish (Uruguay) [es-UY]"
    },
    {
      "value": "es-VE",
      "label": "Spanish (Venezuela) [es-VE]"
    },
    {
      "value": "es",
      "label": "Spanish [es]"
    },
    {
      "value": "su",
      "label": "Sundanese [su]"
    },
    {
      "value": "ss",
      "label": "Swati [ss]"
    },
    {
      "value": "sv-FI",
      "label": "Swedish (Finland) [sv-FI]"
    },
    {
      "value": "sv-SE",
      "label": "Swedish (Sweden) [sv-SE]"
    },
    {
      "value": "sv",
      "label": "Swedish [sv]"
    },
    {
      "value": "ty",
      "label": "Tahitian [ty]"
    },
    {
      "value": "tg",
      "label": "Tajik (Cyrillic) [tg]"
    },
    {
      "value": "ta",
      "label": "Tamil [ta]"
    },
    {
      "value": "tt",
      "label": "Tatar [tt]"
    },
    {
      "value": "te",
      "label": "Telugu [te]"
    },
    {
      "value": "th",
      "label": "Thai [th]"
    },
    {
      "value": "bo",
      "label": "Tibetan [bo]"
    },
    {
      "value": "tig",
      "label": "Tigre [tig]"
    },
    {
      "value": "ti",
      "label": "Tigrinya [ti]"
    },
    {
      "value": "to",
      "label": "Tongan [to]"
    },
    {
      "value": "trs",
      "label": "trs [trs]"
    },
    {
      "value": "ts",
      "label": "Tsonga [ts]"
    },
    {
      "value": "tr",
      "label": "Turkish [tr]"
    },
    {
      "value": "tk",
      "label": "Turkmen [tk]"
    },
    {
      "value": "uk",
      "label": "Ukrainian [uk]"
    },
    {
      "value": "hsb",
      "label": "Upper Sorbian [hsb]"
    },
    {
      "value": "ur",
      "label": "Urdu [ur]"
    },
    {
      "value": "ug",
      "label": "Uyghur [ug]"
    },
    {
      "value": "uz",
      "label": "Uzbek (Latin) [uz]"
    },
    {
      "value": "ve",
      "label": "Venda [ve]"
    },
    {
      "value": "vi",
      "label": "Vietnamese [vi]"
    },
    {
      "value": "vo",
      "label": "Volapük [vo]"
    },
    {
      "value": "wa",
      "label": "Walloon [wa]"
    },
    {
      "value": "cy",
      "label": "Welsh [cy]"
    },
    {
      "value": "wo",
      "label": "Wolof [wo]"
    },
    {
      "value": "xh",
      "label": "Xhosa [xh]"
    },
    {
      "value": "ii",
      "label": "Yi [ii]"
    },
    {
      "value": "yi",
      "label": "Yiddish [yi]"
    },
    {
      "value": "yo",
      "label": "Yoruba [yo]"
    },
    {
      "value": "zam",
      "label": "zam [zam]"
    },
    {
      "value": "za",
      "label": "Zhuang [za]"
    },
    {
      "value": "zu",
      "label": "Zulu [zu]"
    }
  ]
} as const satisfies Record<BrowserLocaleTarget, readonly BrowserLocaleOption[]>;
