// Generated by scripts/build-osm-country-languages.mjs. Do not edit by hand.
// Source catalog:
// - OpenStreetMap Wiki: https://wiki.openstreetmap.org/w/index.php?title=Nominatim/Country_Codes&action=raw

export type OsmCountryLanguageEntry = {
  readonly countryCode: string;
  readonly languageCodes: readonly string[];
};

export const osmCountryLanguageCatalog = [
  {
    "countryCode": "ad",
    "languageCodes": [
      "ca"
    ]
  },
  {
    "countryCode": "ae",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "af",
    "languageCodes": [
      "fa",
      "ps"
    ]
  },
  {
    "countryCode": "ag",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ai",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "al",
    "languageCodes": [
      "sq"
    ]
  },
  {
    "countryCode": "am",
    "languageCodes": [
      "hy"
    ]
  },
  {
    "countryCode": "ao",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "aq",
    "languageCodes": [
      "en",
      "es",
      "fr",
      "ru"
    ]
  },
  {
    "countryCode": "ar",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "as",
    "languageCodes": [
      "en",
      "sm"
    ]
  },
  {
    "countryCode": "at",
    "languageCodes": [
      "de"
    ]
  },
  {
    "countryCode": "au",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "aw",
    "languageCodes": [
      "nl",
      "pap"
    ]
  },
  {
    "countryCode": "ax",
    "languageCodes": [
      "sv"
    ]
  },
  {
    "countryCode": "az",
    "languageCodes": [
      "az"
    ]
  },
  {
    "countryCode": "ba",
    "languageCodes": [
      "bs",
      "hr",
      "sr"
    ]
  },
  {
    "countryCode": "bb",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "bd",
    "languageCodes": [
      "bn"
    ]
  },
  {
    "countryCode": "be",
    "languageCodes": [
      "nl",
      "fr",
      "de"
    ]
  },
  {
    "countryCode": "bf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "bg",
    "languageCodes": [
      "bg"
    ]
  },
  {
    "countryCode": "bh",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "bi",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "bj",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "bl",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "bm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "bn",
    "languageCodes": [
      "ms"
    ]
  },
  {
    "countryCode": "bo",
    "languageCodes": [
      "es",
      "qu",
      "gn",
      "ay"
    ]
  },
  {
    "countryCode": "bq",
    "languageCodes": [
      "nl"
    ]
  },
  {
    "countryCode": "br",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "bs",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "bt",
    "languageCodes": [
      "dz"
    ]
  },
  {
    "countryCode": "bv",
    "languageCodes": [
      "no"
    ]
  },
  {
    "countryCode": "bw",
    "languageCodes": [
      "en",
      "tn"
    ]
  },
  {
    "countryCode": "by",
    "languageCodes": [
      "be",
      "ru"
    ]
  },
  {
    "countryCode": "bz",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ca",
    "languageCodes": [
      "en",
      "fr"
    ]
  },
  {
    "countryCode": "cc",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "cd",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "cf",
    "languageCodes": [
      "fr",
      "sg"
    ]
  },
  {
    "countryCode": "cg",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ch",
    "languageCodes": [
      "de",
      "fr",
      "it",
      "rm"
    ]
  },
  {
    "countryCode": "ci",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ck",
    "languageCodes": [
      "en",
      "rar"
    ]
  },
  {
    "countryCode": "cl",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "cm",
    "languageCodes": [
      "fr",
      "en"
    ]
  },
  {
    "countryCode": "cn",
    "languageCodes": [
      "zh-hans"
    ]
  },
  {
    "countryCode": "co",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "cr",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "cu",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "cv",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "cw",
    "languageCodes": [
      "nl",
      "en"
    ]
  },
  {
    "countryCode": "cx",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "cy",
    "languageCodes": [
      "el",
      "tr"
    ]
  },
  {
    "countryCode": "cz",
    "languageCodes": [
      "cs"
    ]
  },
  {
    "countryCode": "de",
    "languageCodes": [
      "de"
    ]
  },
  {
    "countryCode": "dj",
    "languageCodes": [
      "fr",
      "ar",
      "so",
      "aa"
    ]
  },
  {
    "countryCode": "dk",
    "languageCodes": [
      "da"
    ]
  },
  {
    "countryCode": "dm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "do",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "dz",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "ec",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "ee",
    "languageCodes": [
      "et"
    ]
  },
  {
    "countryCode": "eg",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "eh",
    "languageCodes": [
      "ar",
      "es",
      "fr"
    ]
  },
  {
    "countryCode": "er",
    "languageCodes": [
      "ti",
      "ar",
      "en"
    ]
  },
  {
    "countryCode": "es",
    "languageCodes": [
      "ast",
      "ca",
      "es",
      "eu",
      "gl"
    ]
  },
  {
    "countryCode": "et",
    "languageCodes": [
      "am",
      "om"
    ]
  },
  {
    "countryCode": "fi",
    "languageCodes": [
      "fi",
      "sv",
      "se"
    ]
  },
  {
    "countryCode": "fj",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "fk",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "fm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "fo",
    "languageCodes": [
      "fo",
      "da"
    ]
  },
  {
    "countryCode": "fr",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ga",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "gb",
    "languageCodes": [
      "en",
      "ga",
      "cy",
      "gd",
      "kw"
    ]
  },
  {
    "countryCode": "gd",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ge",
    "languageCodes": [
      "ka"
    ]
  },
  {
    "countryCode": "gf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "gg",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "gh",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "gi",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "gl",
    "languageCodes": [
      "kl",
      "da"
    ]
  },
  {
    "countryCode": "gm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "gn",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "gp",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "gq",
    "languageCodes": [
      "es",
      "fr",
      "pt"
    ]
  },
  {
    "countryCode": "gr",
    "languageCodes": [
      "el"
    ]
  },
  {
    "countryCode": "gs",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "gt",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "gu",
    "languageCodes": [
      "en",
      "ch"
    ]
  },
  {
    "countryCode": "gw",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "gy",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "hk",
    "languageCodes": [
      "zh-hant",
      "en"
    ]
  },
  {
    "countryCode": "hm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "hn",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "hr",
    "languageCodes": [
      "hr"
    ]
  },
  {
    "countryCode": "ht",
    "languageCodes": [
      "fr",
      "ht"
    ]
  },
  {
    "countryCode": "hu",
    "languageCodes": [
      "hu"
    ]
  },
  {
    "countryCode": "id",
    "languageCodes": [
      "id"
    ]
  },
  {
    "countryCode": "ie",
    "languageCodes": [
      "en",
      "ga"
    ]
  },
  {
    "countryCode": "il",
    "languageCodes": [
      "he"
    ]
  },
  {
    "countryCode": "im",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "in",
    "languageCodes": [
      "hi",
      "en"
    ]
  },
  {
    "countryCode": "io",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "iq",
    "languageCodes": [
      "ar",
      "ku"
    ]
  },
  {
    "countryCode": "ir",
    "languageCodes": [
      "fa"
    ]
  },
  {
    "countryCode": "is",
    "languageCodes": [
      "is"
    ]
  },
  {
    "countryCode": "it",
    "languageCodes": [
      "it",
      "de",
      "fr"
    ]
  },
  {
    "countryCode": "je",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "jm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "jo",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "jp",
    "languageCodes": [
      "ja"
    ]
  },
  {
    "countryCode": "ke",
    "languageCodes": [
      "sw",
      "en"
    ]
  },
  {
    "countryCode": "kg",
    "languageCodes": [
      "ky",
      "ru"
    ]
  },
  {
    "countryCode": "kh",
    "languageCodes": [
      "km"
    ]
  },
  {
    "countryCode": "ki",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "km",
    "languageCodes": [
      "ar",
      "fr",
      "sw"
    ]
  },
  {
    "countryCode": "kn",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "kp",
    "languageCodes": [
      "ko"
    ]
  },
  {
    "countryCode": "kr",
    "languageCodes": [
      "ko"
    ]
  },
  {
    "countryCode": "kw",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "ky",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "kz",
    "languageCodes": [
      "kk",
      "ru"
    ]
  },
  {
    "countryCode": "la",
    "languageCodes": [
      "lo"
    ]
  },
  {
    "countryCode": "lb",
    "languageCodes": [
      "ar",
      "fr"
    ]
  },
  {
    "countryCode": "lc",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "li",
    "languageCodes": [
      "de"
    ]
  },
  {
    "countryCode": "lk",
    "languageCodes": [
      "si",
      "ta"
    ]
  },
  {
    "countryCode": "lr",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ls",
    "languageCodes": [
      "en",
      "st"
    ]
  },
  {
    "countryCode": "lt",
    "languageCodes": [
      "lt"
    ]
  },
  {
    "countryCode": "lu",
    "languageCodes": [
      "lb",
      "fr",
      "de"
    ]
  },
  {
    "countryCode": "lv",
    "languageCodes": [
      "lv"
    ]
  },
  {
    "countryCode": "ly",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "ma",
    "languageCodes": [
      "ar",
      "fr",
      "zgh"
    ]
  },
  {
    "countryCode": "mc",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "md",
    "languageCodes": [
      "ro",
      "ru",
      "uk"
    ]
  },
  {
    "countryCode": "me",
    "languageCodes": [
      "srp",
      "sr",
      "hr",
      "bs",
      "sq"
    ]
  },
  {
    "countryCode": "mf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "mg",
    "languageCodes": [
      "mg",
      "fr"
    ]
  },
  {
    "countryCode": "mh",
    "languageCodes": [
      "en",
      "mh"
    ]
  },
  {
    "countryCode": "mk",
    "languageCodes": [
      "mk"
    ]
  },
  {
    "countryCode": "ml",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "mm",
    "languageCodes": [
      "my"
    ]
  },
  {
    "countryCode": "mn",
    "languageCodes": [
      "mn"
    ]
  },
  {
    "countryCode": "mo",
    "languageCodes": [
      "zh-hant",
      "pt"
    ]
  },
  {
    "countryCode": "mp",
    "languageCodes": [
      "en",
      "ch"
    ]
  },
  {
    "countryCode": "mq",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "mr",
    "languageCodes": [
      "ar",
      "fr"
    ]
  },
  {
    "countryCode": "ms",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "mt",
    "languageCodes": [
      "mt",
      "en"
    ]
  },
  {
    "countryCode": "mu",
    "languageCodes": [
      "mfe",
      "fr",
      "en"
    ]
  },
  {
    "countryCode": "mv",
    "languageCodes": [
      "dv"
    ]
  },
  {
    "countryCode": "mw",
    "languageCodes": [
      "en",
      "ny"
    ]
  },
  {
    "countryCode": "mx",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "my",
    "languageCodes": [
      "ms"
    ]
  },
  {
    "countryCode": "mz",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "na",
    "languageCodes": [
      "en",
      "sf",
      "de"
    ]
  },
  {
    "countryCode": "nc",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ne",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "nf",
    "languageCodes": [
      "en",
      "pih"
    ]
  },
  {
    "countryCode": "ng",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ni",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "nl",
    "languageCodes": [
      "nl"
    ]
  },
  {
    "countryCode": "no",
    "languageCodes": [
      "nb",
      "nn",
      "no",
      "se"
    ]
  },
  {
    "countryCode": "np",
    "languageCodes": [
      "ne"
    ]
  },
  {
    "countryCode": "nr",
    "languageCodes": [
      "na",
      "en"
    ]
  },
  {
    "countryCode": "nu",
    "languageCodes": [
      "niu",
      "en"
    ]
  },
  {
    "countryCode": "nz",
    "languageCodes": [
      "mi",
      "en"
    ]
  },
  {
    "countryCode": "om",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "pa",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "pe",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "pf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "pg",
    "languageCodes": [
      "en",
      "tpi",
      "ho"
    ]
  },
  {
    "countryCode": "ph",
    "languageCodes": [
      "en",
      "tl"
    ]
  },
  {
    "countryCode": "pk",
    "languageCodes": [
      "en",
      "ur"
    ]
  },
  {
    "countryCode": "pl",
    "languageCodes": [
      "pl"
    ]
  },
  {
    "countryCode": "pm",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "pn",
    "languageCodes": [
      "en",
      "pih"
    ]
  },
  {
    "countryCode": "pr",
    "languageCodes": [
      "es",
      "en"
    ]
  },
  {
    "countryCode": "ps",
    "languageCodes": [
      "ar",
      "he"
    ]
  },
  {
    "countryCode": "pt",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "pw",
    "languageCodes": [
      "en",
      "pau",
      "ja",
      "sov",
      "tox"
    ]
  },
  {
    "countryCode": "py",
    "languageCodes": [
      "es",
      "gn"
    ]
  },
  {
    "countryCode": "qa",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "re",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ro",
    "languageCodes": [
      "ro"
    ]
  },
  {
    "countryCode": "rs",
    "languageCodes": [
      "sr",
      "sr-Latn"
    ]
  },
  {
    "countryCode": "ru",
    "languageCodes": [
      "ru"
    ]
  },
  {
    "countryCode": "rw",
    "languageCodes": [
      "rw",
      "fr",
      "en"
    ]
  },
  {
    "countryCode": "sa",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "sb",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "sc",
    "languageCodes": [
      "fr",
      "en",
      "crs"
    ]
  },
  {
    "countryCode": "sd",
    "languageCodes": [
      "ar",
      "en"
    ]
  },
  {
    "countryCode": "se",
    "languageCodes": [
      "sv"
    ]
  },
  {
    "countryCode": "sg",
    "languageCodes": [
      "zh-hans",
      "en",
      "ms",
      "ta"
    ]
  },
  {
    "countryCode": "sh",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "si",
    "languageCodes": [
      "sl"
    ]
  },
  {
    "countryCode": "sj",
    "languageCodes": [
      "no"
    ]
  },
  {
    "countryCode": "sk",
    "languageCodes": [
      "sk"
    ]
  },
  {
    "countryCode": "sl",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "sm",
    "languageCodes": [
      "it"
    ]
  },
  {
    "countryCode": "sn",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "so",
    "languageCodes": [
      "so",
      "ar"
    ]
  },
  {
    "countryCode": "sr",
    "languageCodes": [
      "nl"
    ]
  },
  {
    "countryCode": "ss",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "st",
    "languageCodes": [
      "pt"
    ]
  },
  {
    "countryCode": "sv",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "sx",
    "languageCodes": [
      "nl",
      "en"
    ]
  },
  {
    "countryCode": "sy",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "sz",
    "languageCodes": [
      "en",
      "ss"
    ]
  },
  {
    "countryCode": "tc",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "td",
    "languageCodes": [
      "fr",
      "ar"
    ]
  },
  {
    "countryCode": "tf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "tg",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "th",
    "languageCodes": [
      "th"
    ]
  },
  {
    "countryCode": "tj",
    "languageCodes": [
      "tg",
      "ru"
    ]
  },
  {
    "countryCode": "tk",
    "languageCodes": [
      "tkl",
      "en",
      "sm"
    ]
  },
  {
    "countryCode": "tl",
    "languageCodes": [
      "pt",
      "tet"
    ]
  },
  {
    "countryCode": "tm",
    "languageCodes": [
      "tk"
    ]
  },
  {
    "countryCode": "tn",
    "languageCodes": [
      "ar",
      "fr"
    ]
  },
  {
    "countryCode": "to",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "tr",
    "languageCodes": [
      "tr"
    ]
  },
  {
    "countryCode": "tt",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "tv",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "tw",
    "languageCodes": [
      "zh-hant"
    ]
  },
  {
    "countryCode": "tz",
    "languageCodes": [
      "sw",
      "en"
    ]
  },
  {
    "countryCode": "ua",
    "languageCodes": [
      "uk"
    ]
  },
  {
    "countryCode": "ug",
    "languageCodes": [
      "en",
      "sw"
    ]
  },
  {
    "countryCode": "um",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "us",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "uy",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "uz",
    "languageCodes": [
      "uz",
      "kaa"
    ]
  },
  {
    "countryCode": "va",
    "languageCodes": [
      "it"
    ]
  },
  {
    "countryCode": "vc",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "ve",
    "languageCodes": [
      "es"
    ]
  },
  {
    "countryCode": "vg",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "vi",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "vn",
    "languageCodes": [
      "vi"
    ]
  },
  {
    "countryCode": "vu",
    "languageCodes": [
      "bi",
      "en",
      "fr"
    ]
  },
  {
    "countryCode": "wf",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "ws",
    "languageCodes": [
      "sm",
      "en"
    ]
  },
  {
    "countryCode": "xk",
    "languageCodes": [
      "sq",
      "sr"
    ]
  },
  {
    "countryCode": "ye",
    "languageCodes": [
      "ar"
    ]
  },
  {
    "countryCode": "yt",
    "languageCodes": [
      "fr"
    ]
  },
  {
    "countryCode": "za",
    "languageCodes": [
      "en",
      "af",
      "st",
      "tn",
      "xh",
      "zu"
    ]
  },
  {
    "countryCode": "zm",
    "languageCodes": [
      "en"
    ]
  },
  {
    "countryCode": "zw",
    "languageCodes": [
      "en",
      "sn",
      "nd"
    ]
  }
] as const satisfies readonly OsmCountryLanguageEntry[];

export const osmCountryLanguageMap = Object.freeze(
  Object.fromEntries(
    osmCountryLanguageCatalog.map((entry) => [entry.countryCode, entry.languageCodes])
  )
) as Readonly<Record<string, readonly string[]>>;
