declare const __PT_BROWSER_TARGET__: "chromium" | "firefox";
declare const __PT_BUILD_CHANNEL__: "release" | "beta" | "local";
declare const __PT_FX_RUNTIME_TEST_HOST__: string;
declare const __PT_CONFORMANCE_LOCATION_ID__: string;
declare const __PT_FIREFOX_STATE_PORT_ID__: string;
declare const __PT_FX_STATE_CHANGE_EVENT__: string;
declare const __PT_RUNTIME_READY_EVENT_NAME__: string;
declare const __PT_RUNTIME_APPLIED_ATTR__: string;
declare const __PT_RUNTIME_CONFIG_ATTR__: string;
declare const __PT_RUNTIME_PAYLOAD_ATTR__: string;
declare const __PT_RUNTIME_DISABLED_ATTR__: string;
declare const __PT_LOG_EVENT_TYPE__: string;
declare const __PT_SHIM_GUARD_KEY__: string;
declare const __PT_TEMPORAL_HANDOFF_KEY__: string;
declare const __PT_WORKER_PATCH_GUARD_KEY__: string;
declare const __PT_SW_PATCH_GUARD_KEY__: string;
declare const __PT_FX_STATIC_CANDIDATES_KEY__: string;
declare const __PT_SURFACE_USAGE_TYPE__: string;
declare const __PT_SURFACE_ERROR_TYPE__: string;
declare const __PT_SURFACE_USAGE_REG_TYPE__: string;
declare const __PT_SW_REWRITE_TYPE__: string;
declare const __PT_SW_STRICT_ISSUE_TYPE__: string;
declare const __PT_FX_HANDOFF_ATTR__: string;
declare const __PT_FX_HANDOFF_READY_EVENT__: string;
declare const __PT_STRICT_WORKER_PREFIX__: string;
declare const __PT_WORKER_ACK_TYPE__: string;
