import type { ControlDMessages } from "./ui-copy-en";

import { BRAND_DISPLAY_NAME } from "@/shared/brand";
export const controlDPt = {
  title: "Control D",
  featureTitle: "Integração com Control D",
  featureDescription:
    "Sincronize regras regionais com um perfil separado do Control D. Apenas versões beta e locais.",
  open: "Abrir Control D",
  back: "Voltar a Avançado",
  lead: "Envie regras regionais para o Control D. As alterações partem desta extensão.",
  progressLabel: "Progresso da configuração",
  enableLabel: "Ativar integração",
  status: {
    loading: "Carregando",
    disconnected: "Não conectado",
    authError: "Falha de autorização",
    conflict: "Revisão necessária",
    syncError: "Erro de sincronização",
    syncing: "Sincronizando",
    chooseSetup: "Escolha uma configuração",
    review: "Pronto para revisar",
    dnsPending: "Regras sincronizadas · Verifique o DNS",
    active: "Ativo",
  },
  account: {
    title: "Conectar conta",
    description:
      "Use uma chave de API com acesso de escrita. Ela fica nesta instalação, fora de exportações e da sincronização do navegador.",
    placeholder: "Chave de API do Control D",
    connect: "Conectar",
    connectedTitle: "Acesso à API verificado",
    connectedDescription:
      "O acesso à conta funciona. Nenhuma alteração remota foi feita.",
    docs: "Instruções da API",
    permissionDenied: "O acesso à API do Control D não foi concedido.",
  },
  setup: {
    title: "Escolher configuração",
    description: `Crie uma configuração separada ou reconecte uma criada pelo ${BRAND_DISPLAY_NAME}.`,
    none: "Nenhuma configuração compatível encontrada.",
    existing: "Configurações existentes",
    missingEndpoint: "Um endpoint será criado ao aplicar.",
    blocked: "Resolva primeiro os conflitos desta configuração no Control D.",
    useExisting: "Usar esta configuração",
    createNew: "Criar configuração",
    confirmTitle: "Usar esta configuração?",
    confirmDescription:
      "Vincule esta instalação ao perfil selecionado. As alterações remotas exigem revisar e aplicar o plano.",
    folders: (count: number) => `Pastas: ${count}`,
  },
  rules: {
    title: "Revisar alterações",
    description: "Revise este plano antes de alterar recursos gerenciados.",
    preview: "Atualizar prévia",
    apply: "Aplicar alterações",
    repair: "Reparar regras",
    sync: "Sincronizar agora",
    routes: "Rotas personalizadas",
    showRoutes: "Revisar rotas",
    hideRoutes: "Ocultar rotas",
    acceptApproximate: "Aceito as rotas aproximadas desta prévia.",
    upToDate: "As regras estão atualizadas.",
    routeDescription:
      "Altere uma escolha automática apenas se precisar de outra saída.",
  },
  dns: {
    title: "Configurar DNS do navegador",
    description: `Configure o DNS seguro no navegador. O ${BRAND_DISPLAY_NAME} não pode alterá-lo nem verificá-lo automaticamente.`,
    copy: "Copiar resolvedor",
    copied: "Copiado",
    settings: "Abrir configurações de DNS",
    verify: "Verificar no Control D",
    guide: "Instruções",
    confirm: "Verifiquei este resolvedor",
    verified: "DNS verificado",
    verifiedDescription:
      "Você confirmou este endpoint na página de status do Control D.",
    verifiedState: "Verificado",
    unverifiedState: "Não verificado",
  },
  overview: {
    title: "Visão geral da integração",
    account: "Acesso à API",
    rules: "Regras gerenciadas",
    dns: "DNS do navegador",
    review: "Revisar rotas",
    verify: "Verificar DNS novamente",
    setupLabel: (code: string) => `Configuração ${code}`,
    syncedAt: (time: string) => `Sincronizado ${time}`,
  },
  summary: {
    profiles: "Perfis",
    endpoints: "Endpoints",
    folders: "Pastas",
    add: "Adicionar",
    update: "Atualizar",
    remove: "Remover",
  },
  disconnect: {
    action: "Desconectar",
    title: "Desconectar o Control D?",
    description:
      "Esqueça a chave de API e pare a sincronização. Recursos remotos e configurações de DNS permanecem.",
    confirm: "Desconectar",
  },
  common: {
    cancel: "Cancelar",
    continue: "Continuar",
    notYet: "Ainda não",
    working: "Processando…",
    selected: "Selecionado",
    requestFailed: "A solicitação ao Control D falhou.",
    copyFailed: "Não foi possível copiar o resolvedor.",
    applyFirst: "Aplique as alterações para criar um endpoint e um resolvedor.",
    confirmedAt: (time: string) => `Confirmado ${time}`,
  },
  help: {
    account: {
      title: "Sua chave fica aqui",
      body: "Conectar permite à extensão acessar o Control D. A chave fica neste navegador.",
      note: "O acesso de escrita é necessário para criar e atualizar regras regionais.",
    },
    setup: {
      title: "Uma configuração separada",
      body: "Use uma configuração nova ou reconecte uma existente. As demais mantêm suas configurações.",
      note: "As alterações remotas começam ao aplicar o plano revisado.",
    },
    rules: {
      title: "Revisar e aplicar",
      body: "A prévia mostra adições, alterações e remoções planejadas.",
      note: "As alterações afetam os recursos gerenciados desta configuração.",
    },
    dns: {
      title: "Configure o DNS no navegador",
      body: "Copie o resolvedor e use-o como DNS seguro nas configurações do navegador.",
      note: "Verifique a página de status do Control D e confirme este resolvedor aqui.",
    },
    overview: {
      title: "Três verificações",
      body: "O acesso à conta, a sincronização e o DNS são verificados separadamente.",
      note: "Desconectar remove a chave e para a sincronização. O DNS e os recursos remotos permanecem.",
    },
  },
  route: {
    notSynchronized: "Não sincronizado",
    unavailable: "Saída indisponível",
    exact: "Saída mais próxima no mesmo país.",
    approximate: "Saída aproximada. Escolha outra se necessário.",
    skipped: "Excluído da sincronização.",
    change: "Alterar",
    choose: "Escolher saída",
    skip: "Ignorar sincronização",
    ruleCount: (count: number) => `Regras: ${count}`,
    selectLabel: (location: string) => `Saída para ${location}`,
  },
  steps: ["Conta", "Configuração", "Regras", "DNS"],
} satisfies ControlDMessages;
