import type { ControlDMessages } from "./ui-copy-en";

import { BRAND_DISPLAY_NAME } from "@/shared/brand";
export const controlDEs = {
  title: "Control D",
  featureTitle: "Integración con Control D",
  featureDescription:
    "Sincroniza reglas regionales con un perfil de Control D independiente. Solo en versiones beta y locales.",
  open: "Abrir Control D",
  back: "Volver a Avanzado",
  lead: "Envía reglas regionales a Control D. Los cambios parten de esta extensión.",
  progressLabel: "Progreso de configuración",
  enableLabel: "Activar integración",
  status: {
    loading: "Cargando",
    disconnected: "Sin conectar",
    authError: "Error de autorización",
    conflict: "Requiere revisión",
    syncError: "Error de sincronización",
    syncing: "Sincronizando",
    chooseSetup: "Elige una configuración",
    review: "Listo para revisar",
    dnsPending: "Reglas sincronizadas · Verifica DNS",
    active: "Activo",
  },
  account: {
    title: "Conectar cuenta",
    description:
      "Usa una clave API con permiso de escritura. Se guarda en esta instalación y queda fuera de las exportaciones y la sincronización del navegador.",
    placeholder: "Clave API de Control D",
    connect: "Conectar",
    connectedTitle: "Acceso API verificado",
    connectedDescription:
      "El acceso a la cuenta funciona. No se han realizado cambios remotos.",
    docs: "Instrucciones de la API",
    permissionDenied: "No se concedió acceso a la API de Control D.",
  },
  setup: {
    title: "Elegir configuración",
    description: `Crea una configuración independiente o vuelve a conectar una creada por ${BRAND_DISPLAY_NAME}.`,
    none: "No se encontraron configuraciones compatibles.",
    existing: "Configuraciones existentes",
    missingEndpoint: "Se creará un endpoint al aplicar los cambios.",
    blocked: "Resuelve primero los conflictos de esta configuración en Control D.",
    useExisting: "Usar esta configuración",
    createNew: "Crear configuración",
    confirmTitle: "¿Usar esta configuración?",
    confirmDescription:
      "Vincula esta instalación con el perfil seleccionado. Los cambios remotos requieren revisar y aplicar el plan.",
    folders: (count: number) => `Carpetas: ${count}`,
  },
  rules: {
    title: "Revisar cambios",
    description: "Revisa este plan antes de cambiar los recursos administrados.",
    preview: "Actualizar vista previa",
    apply: "Aplicar cambios",
    repair: "Reparar reglas",
    sync: "Sincronizar ahora",
    routes: "Rutas personalizadas",
    showRoutes: "Revisar rutas",
    hideRoutes: "Ocultar rutas",
    acceptApproximate: "Acepto las rutas aproximadas de esta vista previa.",
    upToDate: "Las reglas están actualizadas.",
    routeDescription: "Cambia una selección automática solo si necesitas otra salida.",
  },
  dns: {
    title: "Configurar DNS del navegador",
    description: `Configura DNS seguro en el navegador. ${BRAND_DISPLAY_NAME} no puede cambiarlo ni verificarlo automáticamente.`,
    copy: "Copiar resolvedor",
    copied: "Copiado",
    settings: "Abrir ajustes de DNS",
    verify: "Verificar en Control D",
    guide: "Instrucciones",
    confirm: "He verificado este resolvedor",
    verified: "DNS verificado",
    verifiedDescription:
      "Confirmaste este endpoint en la página de estado de Control D.",
    verifiedState: "Verificado",
    unverifiedState: "Sin verificar",
  },
  overview: {
    title: "Resumen de integración",
    account: "Acceso API",
    rules: "Reglas administradas",
    dns: "DNS del navegador",
    review: "Revisar rutas",
    verify: "Verificar DNS de nuevo",
    setupLabel: (code: string) => `Configuración ${code}`,
    syncedAt: (time: string) => `Sincronizado ${time}`,
  },
  summary: {
    profiles: "Perfiles",
    endpoints: "Endpoints",
    folders: "Carpetas",
    add: "Añadir",
    update: "Actualizar",
    remove: "Eliminar",
  },
  disconnect: {
    action: "Desconectar",
    title: "¿Desconectar Control D?",
    description:
      "Olvida la clave API y detén la sincronización. Los recursos remotos y los ajustes de DNS permanecen.",
    confirm: "Desconectar",
  },
  common: {
    cancel: "Cancelar",
    continue: "Continuar",
    notYet: "Todavía no",
    working: "Procesando…",
    selected: "Seleccionado",
    requestFailed: "La solicitud a Control D falló.",
    copyFailed: "No se pudo copiar el resolvedor.",
    applyFirst: "Aplica los cambios para crear un endpoint y un resolvedor.",
    confirmedAt: (time: string) => `Confirmado ${time}`,
  },
  help: {
    account: {
      title: "Tu clave se queda aquí",
      body: "Conectar permite a la extensión acceder a Control D. La clave permanece en este navegador.",
      note: "Se necesita acceso de escritura para crear y actualizar reglas regionales.",
    },
    setup: {
      title: "Una configuración independiente",
      body: "Usa una configuración nueva o vuelve a conectar una existente. Las demás conservan sus ajustes.",
      note: "Los cambios remotos comienzan al aplicar el plan revisado.",
    },
    rules: {
      title: "Revisar y aplicar",
      body: "La vista previa muestra las adiciones, cambios y eliminaciones previstas.",
      note: "Los cambios afectan a los recursos administrados de esta configuración.",
    },
    dns: {
      title: "Configura DNS en el navegador",
      body: "Copia el resolvedor y úsalo como DNS seguro en los ajustes del navegador.",
      note: "Revisa la página de estado de Control D y confirma aquí este resolvedor.",
    },
    overview: {
      title: "Tres comprobaciones",
      body: "El acceso a la cuenta, la sincronización y el DNS se verifican por separado.",
      note: "Desconectar elimina la clave y detiene la sincronización. El DNS y los recursos remotos permanecen.",
    },
  },
  route: {
    notSynchronized: "Sin sincronizar",
    unavailable: "Salida no disponible",
    exact: "Salida más cercana en el mismo país.",
    approximate: "Salida aproximada. Elige otra si es necesario.",
    skipped: "Excluido de la sincronización.",
    change: "Cambiar",
    choose: "Elegir salida",
    skip: "Omitir sincronización",
    ruleCount: (count: number) => `Reglas: ${count}`,
    selectLabel: (location: string) => `Salida para ${location}`,
  },
  steps: ["Cuenta", "Configuración", "Reglas", "DNS"],
} satisfies ControlDMessages;
